<?php

namespace Talp1\LaravelRegistry\Enums;

use Talp1\LaravelRegistry\Enums\Contracts\CanBeCollected;
use Talp1\LaravelRegistry\Enums\Contracts\HasLabels;
use Talp1\LaravelRegistry\Enums\Traits\CanBeCollected as CanBeCollectedTrait;
use Talp1\LaravelRegistry\Enums\Traits\ConvertsValueToLabel;

/** @implements CanBeCollected<string> */
enum Countries: string implements CanBeCollected, HasLabels {
    /** @use CanBeCollectedTrait<string> */
    use CanBeCollectedTrait, ConvertsValueToLabel;

    case AFGHANISTAN = 'afghanistan';
    case ALBANIA = 'albania';
    case ALGERIA = 'algeria';
    case ANDORRA = 'andorra';
    case ANGOLA = 'angola';
    case ANTIGUA_AND_BARBUDA = 'antigua and barbuda';
    case ARGENTINA = 'argentina';
    case ARMENIA = 'armenia';
    case AUSTRALIA = 'australia';
    case AUSTRIA = 'austria';
    case AZERBAIJAN = 'azerbaijan';
    case BAHAMAS = 'bahamas';
    case BAHRAIN = 'bahrain';
    case BANGLADESH = 'bangladesh';
    case BARBADOS = 'barbados';
    case BELARUS = 'belarus';
    case BELGIUM = 'belgium';
    case BELIZE = 'belize';
    case BENIN = 'benin';
    case BHUTAN = 'bhutan';
    case BOLIVIA = 'bolivia';
    case BOSNIA_AND_HERZEGOVINA = 'bosnia and herzegovina';
    case BOTSWANA = 'botswana';
    case BRAZIL = 'brazil';
    case BRUNEI = 'brunei';
    case BULGARIA = 'bulgaria';
    case BURKINA_FASO = 'burkina faso';
    case BURUNDI = 'burundi';
    case CABO_VERDE = 'cabo verde';
    case CAMBODIA = 'cambodia';
    case CAMEROON = 'cameroon';
    case CANADA = 'canada';
    case CENTRAL_AFRICAN_REPUBLIC = 'central african republic';
    case CHAD = 'chad';
    case CHILE = 'chile';
    case CHINA = 'china';
    case COLOMBIA = 'colombia';
    case COMOROS = 'comoros';
    case CONGO_DEMOCRATIC_REPUBLIC = 'congo democratic republic';
    case CONGO_REPUBLIC = 'congo republic';
    case COSTA_RICA = 'costa rica';
    case CROATIA = 'croatia';
    case CUBA = 'cuba';
    case CYPRUS = 'cyprus';
    case CZECH_REPUBLIC = 'czech republic';
    case DENMARK = 'denmark';
    case DJIBOUTI = 'djibouti';
    case DOMINICA = 'dominica';
    case DOMINICAN_REPUBLIC = 'dominican republic';
    case ECUADOR = 'ecuador';
    case EGYPT = 'egypt';
    case EL_SALVADOR = 'el salvador';
    case EQUATORIAL_GUINEA = 'equatorial guinea';
    case ERITREA = 'eritrea';
    case ESTONIA = 'estonia';
    case ESWATINI = 'eswatini';
    case ETHIOPIA = 'ethiopia';
    case FIJI = 'fiji';
    case FINLAND = 'finland';
    case FRANCE = 'france';
    case GABON = 'gabon';
    case GAMBIA = 'gambia';
    case GEORGIA = 'georgia';
    case GERMANY = 'germany';
    case GHANA = 'ghana';
    case GREECE = 'greece';
    case GRENADA = 'grenada';
    case GUATEMALA = 'guatemala';
    case GUINEA = 'guinea';
    case GUINEA_BISSAU = 'guinea bissau';
    case GUYANA = 'guyana';
    case HAITI = 'haiti';
    case HONDURAS = 'honduras';
    case HUNGARY = 'hungary';
    case ICELAND = 'iceland';
    case INDIA = 'india';
    case INDONESIA = 'indonesia';
    case IRAN = 'iran';
    case IRAQ = 'iraq';
    case IRELAND = 'ireland';
    case ISRAEL = 'israel';
    case ITALY = 'italy';
    case JAMAICA = 'jamaica';
    case JAPAN = 'japan';
    case JORDAN = 'jordan';
    case KAZAKHSTAN = 'kazakhstan';
    case KENYA = 'kenya';
    case KIRIBATI = 'kiribati';
    case KOREA_NORTH = 'korea north';
    case KOREA_SOUTH = 'korea south';
    case KOSOVO = 'kosovo';
    case KUWAIT = 'kuwait';
    case KYRGYZSTAN = 'kyrgyzstan';
    case LAOS = 'laos';
    case LATVIA = 'latvia';
    case LEBANON = 'lebanon';
    case LESOTHO = 'lesotho';
    case LIBERIA = 'liberia';
    case LIBYA = 'libya';
    case LIECHTENSTEIN = 'liechtenstein';
    case LITHUANIA = 'lithuania';
    case LUXEMBOURG = 'luxembourg';
    case MADAGASCAR = 'madagascar';
    case MALAWI = 'malawi';
    case MALAYSIA = 'malaysia';
    case MALDIVES = 'maldives';
    case MALI = 'mali';
    case MALTA = 'malta';
    case MARSHALL_ISLANDS = 'marshall islands';
    case MAURITANIA = 'mauritania';
    case MAURITIUS = 'mauritius';
    case MEXICO = 'mexico';
    case MICRONESIA = 'micronesia';
    case MOLDOVA = 'moldova';
    case MONACO = 'monaco';
    case MONGOLIA = 'mongolia';
    case MONTENEGRO = 'montenegro';
    case MOROCCO = 'morocco';
    case MOZAMBIQUE = 'mozambique';
    case MYANMAR = 'myanmar';
    case NAMIBIA = 'namibia';
    case NAURU = 'nauru';
    case NEPAL = 'nepal';
    case NETHERLANDS = 'netherlands';
    case NEW_ZEALAND = 'new zealand';
    case NICARAGUA = 'nicaragua';
    case NIGER = 'niger';
    case NIGERIA = 'nigeria';
    case NORTH_MACEDONIA = 'north macedonia';
    case NORWAY = 'norway';
    case OMAN = 'oman';
    case PAKISTAN = 'pakistan';
    case PALAU = 'palau';
    case PALESTINE = 'palestine';
    case PANAMA = 'panama';
    case PAPUA_NEW_GUINEA = 'papua new guinea';
    case PARAGUAY = 'paraguay';
    case PERU = 'peru';
    case PHILIPPINES = 'philippines';
    case POLAND = 'poland';
    case PORTUGAL = 'portugal';
    case QATAR = 'qatar';
    case ROMANIA = 'romania';
    case RUSSIA = 'russia';
    case RWANDA = 'rwanda';
    case SAINT_KITTS_AND_NEVIS = 'saint kitts and nevis';
    case SAINT_LUCIA = 'saint lucia';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'saint vincent and the grenadines';
    case SAMOA = 'samoa';
    case SAN_MARINO = 'san marino';
    case SAO_TOME_AND_PRINCIPE = 'sao tome and principe';
    case SAUDI_ARABIA = 'saudi arabia';
    case SENEGAL = 'senegal';
    case SERBIA = 'serbia';
    case SEYCHELLES = 'seychelles';
    case SIERRA_LEONE = 'sierra leone';
    case SINGAPORE = 'singapore';
    case SLOVAKIA = 'slovakia';
    case SLOVENIA = 'slovenia';
    case SOLOMON_ISLANDS = 'solomon islands';
    case SOMALIA = 'somalia';
    case SOUTH_AFRICA = 'south africa';
    case SOUTH_SUDAN = 'south sudan';
    case SPAIN = 'spain';
    case SRI_LANKA = 'sri lanka';
    case SUDAN = 'sudan';
    case SURINAME = 'suriname';
    case SWEDEN = 'sweden';
    case SWITZERLAND = 'switzerland';
    case SYRIA = 'syria';
    case TAIWAN = 'taiwan';
    case TAJIKISTAN = 'tajikistan';
    case TANZANIA = 'tanzania';
    case THAILAND = 'thailand';
    case TIMOR_LESTE = 'timor leste';
    case TOGO = 'togo';
    case TONGA = 'tonga';
    case TRINIDAD_AND_TOBAGO = 'trinidad and tobago';
    case TUNISIA = 'tunisia';
    case TURKEY = 'turkey';
    case TURKMENISTAN = 'turkmenistan';
    case TUVALU = 'tuvalu';
    case UGANDA = 'uganda';
    case UKRAINE = 'ukraine';
    case UNITED_ARAB_EMIRATES = 'united arab emirates';
    case UNITED_KINGDOM = 'united kingdom';
    case UNITED_STATES = 'united states';
    case URUGUAY = 'uruguay';
    case UZBEKISTAN = 'uzbekistan';
    case VANUATU = 'vanuatu';
    case VATICAN_CITY = 'vatican city';
    case VENEZUELA = 'venezuela';
    case VIETNAM = 'vietnam';
    case YEMEN = 'yemen';
    case ZAMBIA = 'zambia';
    case ZIMBABWE = 'zimbabwe';

    public function iso3166Alpha2Code(): string {
        return match ($this) {
            self::AFGHANISTAN => 'AF',
            self::ALBANIA => 'AL',
            self::ALGERIA => 'DZ',
            self::ANDORRA => 'AD',
            self::ANGOLA => 'AO',
            self::ANTIGUA_AND_BARBUDA => 'AG',
            self::ARGENTINA => 'AR',
            self::ARMENIA => 'AM',
            self::AUSTRALIA => 'AU',
            self::AUSTRIA => 'AT',
            self::AZERBAIJAN => 'AZ',
            self::BAHAMAS => 'BS',
            self::BAHRAIN => 'BH',
            self::BANGLADESH => 'BD',
            self::BARBADOS => 'BB',
            self::BELARUS => 'BY',
            self::BELGIUM => 'BE',
            self::BELIZE => 'BZ',
            self::BENIN => 'BJ',
            self::BHUTAN => 'BT',
            self::BOLIVIA => 'BO',
            self::BOSNIA_AND_HERZEGOVINA => 'BA',
            self::BOTSWANA => 'BW',
            self::BRAZIL => 'BR',
            self::BRUNEI => 'BN',
            self::BULGARIA => 'BG',
            self::BURKINA_FASO => 'BF',
            self::BURUNDI => 'BI',
            self::CABO_VERDE => 'CV',
            self::CAMBODIA => 'KH',
            self::CAMEROON => 'CM',
            self::CANADA => 'CA',
            self::CENTRAL_AFRICAN_REPUBLIC => 'CF',
            self::CHAD => 'TD',
            self::CHILE => 'CL',
            self::CHINA => 'CN',
            self::COLOMBIA => 'CO',
            self::COMOROS => 'KM',
            self::CONGO_DEMOCRATIC_REPUBLIC => 'CD',
            self::CONGO_REPUBLIC => 'CG',
            self::COSTA_RICA => 'CR',
            self::CROATIA => 'HR',
            self::CUBA => 'CU',
            self::CYPRUS => 'CY',
            self::CZECH_REPUBLIC => 'CZ',
            self::DENMARK => 'DK',
            self::DJIBOUTI => 'DJ',
            self::DOMINICA => 'DM',
            self::DOMINICAN_REPUBLIC => 'DO',
            self::ECUADOR => 'EC',
            self::EGYPT => 'EG',
            self::EL_SALVADOR => 'SV',
            self::EQUATORIAL_GUINEA => 'GQ',
            self::ERITREA => 'ER',
            self::ESTONIA => 'EE',
            self::ESWATINI => 'SZ',
            self::ETHIOPIA => 'ET',
            self::FIJI => 'FJ',
            self::FINLAND => 'FI',
            self::FRANCE => 'FR',
            self::GABON => 'GA',
            self::GAMBIA => 'GM',
            self::GEORGIA => 'GE',
            self::GERMANY => 'DE',
            self::GHANA => 'GH',
            self::GREECE => 'GR',
            self::GRENADA => 'GD',
            self::GUATEMALA => 'GT',
            self::GUINEA => 'GN',
            self::GUINEA_BISSAU => 'GW',
            self::GUYANA => 'GY',
            self::HAITI => 'HT',
            self::HONDURAS => 'HN',
            self::HUNGARY => 'HU',
            self::ICELAND => 'IS',
            self::INDIA => 'IN',
            self::INDONESIA => 'ID',
            self::IRAN => 'IR',
            self::IRAQ => 'IQ',
            self::IRELAND => 'IE',
            self::ISRAEL => 'IL',
            self::ITALY => 'IT',
            self::JAMAICA => 'JM',
            self::JAPAN => 'JP',
            self::JORDAN => 'JO',
            self::KAZAKHSTAN => 'KZ',
            self::KENYA => 'KE',
            self::KIRIBATI => 'KI',
            self::KOREA_NORTH => 'KP',
            self::KOREA_SOUTH => 'KR',
            self::KOSOVO => 'XK',
            self::KUWAIT => 'KW',
            self::KYRGYZSTAN => 'KG',
            self::LAOS => 'LA',
            self::LATVIA => 'LV',
            self::LEBANON => 'LB',
            self::LESOTHO => 'LS',
            self::LIBERIA => 'LR',
            self::LIBYA => 'LY',
            self::LIECHTENSTEIN => 'LI',
            self::LITHUANIA => 'LT',
            self::LUXEMBOURG => 'LU',
            self::MADAGASCAR => 'MG',
            self::MALAWI => 'MW',
            self::MALAYSIA => 'MY',
            self::MALDIVES => 'MV',
            self::MALI => 'ML',
            self::MALTA => 'MT',
            self::MARSHALL_ISLANDS => 'MH',
            self::MAURITANIA => 'MR',
            self::MAURITIUS => 'MU',
            self::MEXICO => 'MX',
            self::MICRONESIA => 'FM',
            self::MOLDOVA => 'MD',
            self::MONACO => 'MC',
            self::MONGOLIA => 'MN',
            self::MONTENEGRO => 'ME',
            self::MOROCCO => 'MA',
            self::MOZAMBIQUE => 'MZ',
            self::MYANMAR => 'MM',
            self::NAMIBIA => 'NA',
            self::NAURU => 'NR',
            self::NEPAL => 'NP',
            self::NETHERLANDS => 'NL',
            self::NEW_ZEALAND => 'NZ',
            self::NICARAGUA => 'NI',
            self::NIGER => 'NE',
            self::NIGERIA => 'NG',
            self::NORTH_MACEDONIA => 'MK',
            self::NORWAY => 'NO',
            self::OMAN => 'OM',
            self::PAKISTAN => 'PK',
            self::PALAU => 'PW',
            self::PALESTINE => 'PS',
            self::PANAMA => 'PA',
            self::PAPUA_NEW_GUINEA => 'PG',
            self::PARAGUAY => 'PY',
            self::PERU => 'PE',
            self::PHILIPPINES => 'PH',
            self::POLAND => 'PL',
            self::PORTUGAL => 'PT',
            self::QATAR => 'QA',
            self::ROMANIA => 'RO',
            self::RUSSIA => 'RU',
            self::RWANDA => 'RW',
            self::SAINT_KITTS_AND_NEVIS => 'KN',
            self::SAINT_LUCIA => 'LC',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'VC',
            self::SAMOA => 'WS',
            self::SAN_MARINO => 'SM',
            self::SAO_TOME_AND_PRINCIPE => 'ST',
            self::SAUDI_ARABIA => 'SA',
            self::SENEGAL => 'SN',
            self::SERBIA => 'RS',
            self::SEYCHELLES => 'SC',
            self::SIERRA_LEONE => 'SL',
            self::SINGAPORE => 'SG',
            self::SLOVAKIA => 'SK',
            self::SLOVENIA => 'SI',
            self::SOLOMON_ISLANDS => 'SB',
            self::SOMALIA => 'SO',
            self::SOUTH_AFRICA => 'ZA',
            self::SOUTH_SUDAN => 'SS',
            self::SPAIN => 'ES',
            self::SRI_LANKA => 'LK',
            self::SUDAN => 'SD',
            self::SURINAME => 'SR',
            self::SWEDEN => 'SE',
            self::SWITZERLAND => 'CH',
            self::SYRIA => 'SY',
            self::TAIWAN => 'TW',
            self::TAJIKISTAN => 'TJ',
            self::TANZANIA => 'TZ',
            self::THAILAND => 'TH',
            self::TIMOR_LESTE => 'TL',
            self::TOGO => 'TG',
            self::TONGA => 'TO',
            self::TRINIDAD_AND_TOBAGO => 'TT',
            self::TUNISIA => 'TN',
            self::TURKEY => 'TR',
            self::TURKMENISTAN => 'TM',
            self::TUVALU => 'TV',
            self::UGANDA => 'UG',
            self::UKRAINE => 'UA',
            self::UNITED_ARAB_EMIRATES => 'AE',
            self::UNITED_KINGDOM => 'GB',
            self::UNITED_STATES => 'US',
            self::URUGUAY => 'UY',
            self::UZBEKISTAN => 'UZ',
            self::VANUATU => 'VU',
            self::VATICAN_CITY => 'VA',
            self::VENEZUELA => 'VE',
            self::VIETNAM => 'VN',
            self::YEMEN => 'YE',
            self::ZAMBIA => 'ZM',
            self::ZIMBABWE => 'ZW',
        };
    }

    public function iso3166Alpha3Code(): string {
        return match ($this) {
            self::AFGHANISTAN => 'AFG',
            self::ALBANIA => 'ALB',
            self::ALGERIA => 'DZA',
            self::ANDORRA => 'AND',
            self::ANGOLA => 'AGO',
            self::ANTIGUA_AND_BARBUDA => 'ATG',
            self::ARGENTINA => 'ARG',
            self::ARMENIA => 'ARM',
            self::AUSTRALIA => 'AUS',
            self::AUSTRIA => 'AUT',
            self::AZERBAIJAN => 'AZE',
            self::BAHAMAS => 'BHS',
            self::BAHRAIN => 'BHR',
            self::BANGLADESH => 'BGD',
            self::BARBADOS => 'BRB',
            self::BELARUS => 'BLR',
            self::BELGIUM => 'BEL',
            self::BELIZE => 'BLZ',
            self::BENIN => 'BEN',
            self::BHUTAN => 'BTN',
            self::BOLIVIA => 'BOL',
            self::BOSNIA_AND_HERZEGOVINA => 'BIH',
            self::BOTSWANA => 'BWA',
            self::BRAZIL => 'BRA',
            self::BRUNEI => 'BRN',
            self::BULGARIA => 'BGR',
            self::BURKINA_FASO => 'BFA',
            self::BURUNDI => 'BDI',
            self::CABO_VERDE => 'CPV',
            self::CAMBODIA => 'KHM',
            self::CAMEROON => 'CMR',
            self::CANADA => 'CAN',
            self::CENTRAL_AFRICAN_REPUBLIC => 'CAF',
            self::CHAD => 'TCD',
            self::CHILE => 'CHL',
            self::CHINA => 'CHN',
            self::COLOMBIA => 'COL',
            self::COMOROS => 'COM',
            self::CONGO_DEMOCRATIC_REPUBLIC => 'COD',
            self::CONGO_REPUBLIC => 'COG',
            self::COSTA_RICA => 'CRI',
            self::CROATIA => 'HRV',
            self::CUBA => 'CUB',
            self::CYPRUS => 'CYP',
            self::CZECH_REPUBLIC => 'CZE',
            self::DENMARK => 'DNK',
            self::DJIBOUTI => 'DJI',
            self::DOMINICA => 'DMA',
            self::DOMINICAN_REPUBLIC => 'DOM',
            self::ECUADOR => 'ECU',
            self::EGYPT => 'EGY',
            self::EL_SALVADOR => 'SLV',
            self::EQUATORIAL_GUINEA => 'GNQ',
            self::ERITREA => 'ERI',
            self::ESTONIA => 'EST',
            self::ESWATINI => 'SWZ',
            self::ETHIOPIA => 'ETH',
            self::FIJI => 'FJI',
            self::FINLAND => 'FIN',
            self::FRANCE => 'FRA',
            self::GABON => 'GAB',
            self::GAMBIA => 'GMB',
            self::GEORGIA => 'GEO',
            self::GERMANY => 'DEU',
            self::GHANA => 'GHA',
            self::GREECE => 'GRC',
            self::GRENADA => 'GRD',
            self::GUATEMALA => 'GTM',
            self::GUINEA => 'GIN',
            self::GUINEA_BISSAU => 'GNB',
            self::GUYANA => 'GUY',
            self::HAITI => 'HTI',
            self::HONDURAS => 'HND',
            self::HUNGARY => 'HUN',
            self::ICELAND => 'ISL',
            self::INDIA => 'IND',
            self::INDONESIA => 'IDN',
            self::IRAN => 'IRN',
            self::IRAQ => 'IRQ',
            self::IRELAND => 'IRL',
            self::ISRAEL => 'ISR',
            self::ITALY => 'ITA',
            self::JAMAICA => 'JAM',
            self::JAPAN => 'JPN',
            self::JORDAN => 'JOR',
            self::KAZAKHSTAN => 'KAZ',
            self::KENYA => 'KEN',
            self::KIRIBATI => 'KIR',
            self::KOREA_NORTH => 'PRK',
            self::KOREA_SOUTH => 'KOR',
            self::KOSOVO => 'XKX',
            self::KUWAIT => 'KWT',
            self::KYRGYZSTAN => 'KGZ',
            self::LAOS => 'LAO',
            self::LATVIA => 'LVA',
            self::LEBANON => 'LBN',
            self::LESOTHO => 'LSO',
            self::LIBERIA => 'LBR',
            self::LIBYA => 'LBY',
            self::LIECHTENSTEIN => 'LIE',
            self::LITHUANIA => 'LTU',
            self::LUXEMBOURG => 'LUX',
            self::MADAGASCAR => 'MDG',
            self::MALAWI => 'MWI',
            self::MALAYSIA => 'MYS',
            self::MALDIVES => 'MDV',
            self::MALI => 'MLI',
            self::MALTA => 'MLT',
            self::MARSHALL_ISLANDS => 'MHL',
            self::MAURITANIA => 'MRT',
            self::MAURITIUS => 'MUS',
            self::MEXICO => 'MEX',
            self::MICRONESIA => 'FSM',
            self::MOLDOVA => 'MDA',
            self::MONACO => 'MCO',
            self::MONGOLIA => 'MNG',
            self::MONTENEGRO => 'MNE',
            self::MOROCCO => 'MAR',
            self::MOZAMBIQUE => 'MOZ',
            self::MYANMAR => 'MMR',
            self::NAMIBIA => 'NAM',
            self::NAURU => 'NRU',
            self::NEPAL => 'NPL',
            self::NETHERLANDS => 'NLD',
            self::NEW_ZEALAND => 'NZL',
            self::NICARAGUA => 'NIC',
            self::NIGER => 'NER',
            self::NIGERIA => 'NGA',
            self::NORTH_MACEDONIA => 'MKD',
            self::NORWAY => 'NOR',
            self::OMAN => 'OMN',
            self::PAKISTAN => 'PAK',
            self::PALAU => 'PLW',
            self::PALESTINE => 'PSE',
            self::PANAMA => 'PAN',
            self::PAPUA_NEW_GUINEA => 'PNG',
            self::PARAGUAY => 'PRY',
            self::PERU => 'PER',
            self::PHILIPPINES => 'PHL',
            self::POLAND => 'POL',
            self::PORTUGAL => 'PRT',
            self::QATAR => 'QAT',
            self::ROMANIA => 'ROU',
            self::RUSSIA => 'RUS',
            self::RWANDA => 'RWA',
            self::SAINT_KITTS_AND_NEVIS => 'KNA',
            self::SAINT_LUCIA => 'LCA',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'VCT',
            self::SAMOA => 'WSM',
            self::SAN_MARINO => 'SMR',
            self::SAO_TOME_AND_PRINCIPE => 'STP',
            self::SAUDI_ARABIA => 'SAU',
            self::SENEGAL => 'SEN',
            self::SERBIA => 'SRB',
            self::SEYCHELLES => 'SYC',
            self::SIERRA_LEONE => 'SLE',
            self::SINGAPORE => 'SGP',
            self::SLOVAKIA => 'SVK',
            self::SLOVENIA => 'SVN',
            self::SOLOMON_ISLANDS => 'SLB',
            self::SOMALIA => 'SOM',
            self::SOUTH_AFRICA => 'ZAF',
            self::SOUTH_SUDAN => 'SSD',
            self::SPAIN => 'ESP',
            self::SRI_LANKA => 'LKA',
            self::SUDAN => 'SDN',
            self::SURINAME => 'SUR',
            self::SWEDEN => 'SWE',
            self::SWITZERLAND => 'CHE',
            self::SYRIA => 'SYR',
            self::TAIWAN => 'TWN',
            self::TAJIKISTAN => 'TJK',
            self::TANZANIA => 'TZA',
            self::THAILAND => 'THA',
            self::TIMOR_LESTE => 'TLS',
            self::TOGO => 'TGO',
            self::TONGA => 'TON',
            self::TRINIDAD_AND_TOBAGO => 'TTO',
            self::TUNISIA => 'TUN',
            self::TURKEY => 'TUR',
            self::TURKMENISTAN => 'TKM',
            self::TUVALU => 'TUV',
            self::UGANDA => 'UGA',
            self::UKRAINE => 'UKR',
            self::UNITED_ARAB_EMIRATES => 'ARE',
            self::UNITED_KINGDOM => 'GBR',
            self::UNITED_STATES => 'USA',
            self::URUGUAY => 'URY',
            self::UZBEKISTAN => 'UZB',
            self::VANUATU => 'VUT',
            self::VATICAN_CITY => 'VAT',
            self::VENEZUELA => 'VEN',
            self::VIETNAM => 'VNM',
            self::YEMEN => 'YEM',
            self::ZAMBIA => 'ZMB',
            self::ZIMBABWE => 'ZWE',
        };
    }

    public function iso3166NumericCode(): string {
        return match ($this) {
            self::AFGHANISTAN => '004',
            self::ALBANIA => '008',
            self::ALGERIA => '012',
            self::ANDORRA => '020',
            self::ANGOLA => '024',
            self::ANTIGUA_AND_BARBUDA => '028',
            self::ARGENTINA => '032',
            self::ARMENIA => '051',
            self::AUSTRALIA => '036',
            self::AUSTRIA => '040',
            self::AZERBAIJAN => '031',
            self::BAHAMAS => '044',
            self::BAHRAIN => '048',
            self::BANGLADESH => '050',
            self::BARBADOS => '052',
            self::BELARUS => '112',
            self::BELGIUM => '056',
            self::BELIZE => '084',
            self::BENIN => '204',
            self::BHUTAN => '064',
            self::BOLIVIA => '068',
            self::BOSNIA_AND_HERZEGOVINA => '070',
            self::BOTSWANA => '072',
            self::BRAZIL => '076',
            self::BRUNEI => '096',
            self::BULGARIA => '100',
            self::BURKINA_FASO => '854',
            self::BURUNDI => '108',
            self::CABO_VERDE => '132',
            self::CAMBODIA => '116',
            self::CAMEROON => '120',
            self::CANADA => '124',
            self::CENTRAL_AFRICAN_REPUBLIC => '140',
            self::CHAD => '148',
            self::CHILE => '152',
            self::CHINA => '156',
            self::COLOMBIA => '170',
            self::COMOROS => '174',
            self::CONGO_DEMOCRATIC_REPUBLIC => '180',
            self::CONGO_REPUBLIC => '178',
            self::COSTA_RICA => '188',
            self::CROATIA => '191',
            self::CUBA => '192',
            self::CYPRUS => '196',
            self::CZECH_REPUBLIC => '203',
            self::DENMARK => '208',
            self::DJIBOUTI => '262',
            self::DOMINICA => '212',
            self::DOMINICAN_REPUBLIC => '214',
            self::ECUADOR => '218',
            self::EGYPT => '818',
            self::EL_SALVADOR => '222',
            self::EQUATORIAL_GUINEA => '226',
            self::ERITREA => '232',
            self::ESTONIA => '233',
            self::ESWATINI => '748',
            self::ETHIOPIA => '231',
            self::FIJI => '242',
            self::FINLAND => '246',
            self::FRANCE => '250',
            self::GABON => '266',
            self::GAMBIA => '270',
            self::GEORGIA => '268',
            self::GERMANY => '276',
            self::GHANA => '288',
            self::GREECE => '300',
            self::GRENADA => '308',
            self::GUATEMALA => '320',
            self::GUINEA => '324',
            self::GUINEA_BISSAU => '624',
            self::GUYANA => '328',
            self::HAITI => '332',
            self::HONDURAS => '340',
            self::HUNGARY => '348',
            self::ICELAND => '352',
            self::INDIA => '356',
            self::INDONESIA => '360',
            self::IRAN => '364',
            self::IRAQ => '368',
            self::IRELAND => '372',
            self::ISRAEL => '376',
            self::ITALY => '380',
            self::JAMAICA => '388',
            self::JAPAN => '392',
            self::JORDAN => '400',
            self::KAZAKHSTAN => '398',
            self::KENYA => '404',
            self::KIRIBATI => '296',
            self::KOREA_NORTH => '408',
            self::KOREA_SOUTH => '410',
            self::KOSOVO => '383',
            self::KUWAIT => '414',
            self::KYRGYZSTAN => '417',
            self::LAOS => '418',
            self::LATVIA => '428',
            self::LEBANON => '422',
            self::LESOTHO => '426',
            self::LIBERIA => '430',
            self::LIBYA => '434',
            self::LIECHTENSTEIN => '438',
            self::LITHUANIA => '440',
            self::LUXEMBOURG => '442',
            self::MADAGASCAR => '450',
            self::MALAWI => '454',
            self::MALAYSIA => '458',
            self::MALDIVES => '462',
            self::MALI => '466',
            self::MALTA => '470',
            self::MARSHALL_ISLANDS => '584',
            self::MAURITANIA => '478',
            self::MAURITIUS => '480',
            self::MEXICO => '484',
            self::MICRONESIA => '583',
            self::MOLDOVA => '498',
            self::MONACO => '492',
            self::MONGOLIA => '496',
            self::MONTENEGRO => '499',
            self::MOROCCO => '504',
            self::MOZAMBIQUE => '508',
            self::MYANMAR => '104',
            self::NAMIBIA => '516',
            self::NAURU => '520',
            self::NEPAL => '524',
            self::NETHERLANDS => '528',
            self::NEW_ZEALAND => '554',
            self::NICARAGUA => '558',
            self::NIGER => '562',
            self::NIGERIA => '566',
            self::NORTH_MACEDONIA => '807',
            self::NORWAY => '578',
            self::OMAN => '512',
            self::PAKISTAN => '586',
            self::PALAU => '585',
            self::PALESTINE => '275',
            self::PANAMA => '591',
            self::PAPUA_NEW_GUINEA => '598',
            self::PARAGUAY => '600',
            self::PERU => '604',
            self::PHILIPPINES => '608',
            self::POLAND => '616',
            self::PORTUGAL => '620',
            self::QATAR => '634',
            self::ROMANIA => '642',
            self::RUSSIA => '643',
            self::RWANDA => '646',
            self::SAINT_KITTS_AND_NEVIS => '659',
            self::SAINT_LUCIA => '662',
            self::SAINT_VINCENT_AND_THE_GRENADINES => '670',
            self::SAMOA => '882',
            self::SAN_MARINO => '674',
            self::SAO_TOME_AND_PRINCIPE => '678',
            self::SAUDI_ARABIA => '682',
            self::SENEGAL => '686',
            self::SERBIA => '688',
            self::SEYCHELLES => '690',
            self::SIERRA_LEONE => '694',
            self::SINGAPORE => '702',
            self::SLOVAKIA => '703',
            self::SLOVENIA => '705',
            self::SOLOMON_ISLANDS => '090',
            self::SOMALIA => '706',
            self::SOUTH_AFRICA => '710',
            self::SOUTH_SUDAN => '728',
            self::SPAIN => '724',
            self::SRI_LANKA => '144',
            self::SUDAN => '729',
            self::SURINAME => '740',
            self::SWEDEN => '752',
            self::SWITZERLAND => '756',
            self::SYRIA => '760',
            self::TAIWAN => '158',
            self::TAJIKISTAN => '762',
            self::TANZANIA => '834',
            self::THAILAND => '764',
            self::TIMOR_LESTE => '626',
            self::TOGO => '768',
            self::TONGA => '776',
            self::TRINIDAD_AND_TOBAGO => '780',
            self::TUNISIA => '788',
            self::TURKEY => '792',
            self::TURKMENISTAN => '795',
            self::TUVALU => '798',
            self::UGANDA => '800',
            self::UKRAINE => '804',
            self::UNITED_ARAB_EMIRATES => '784',
            self::UNITED_KINGDOM => '826',
            self::UNITED_STATES => '840',
            self::URUGUAY => '858',
            self::UZBEKISTAN => '860',
            self::VANUATU => '548',
            self::VATICAN_CITY => '336',
            self::VENEZUELA => '862',
            self::VIETNAM => '704',
            self::YEMEN => '887',
            self::ZAMBIA => '894',
            self::ZIMBABWE => '716',
        };
    }

    public function phonePrefix(): string {
        return match ($this) {
            self::AFGHANISTAN => '93',
            self::ALBANIA => '355',
            self::ALGERIA => '213',
            self::ANDORRA => '376',
            self::ANGOLA => '244',
            self::ANTIGUA_AND_BARBUDA => '1-268',
            self::ARGENTINA => '54',
            self::ARMENIA => '374',
            self::AUSTRALIA => '61',
            self::AUSTRIA => '43',
            self::AZERBAIJAN => '994',
            self::BAHAMAS => '1-242',
            self::BAHRAIN => '973',
            self::BANGLADESH => '880',
            self::BARBADOS => '1-246',
            self::BELARUS => '375',
            self::BELGIUM => '32',
            self::BELIZE => '501',
            self::BENIN => '229',
            self::BHUTAN => '975',
            self::BOLIVIA => '591',
            self::BOSNIA_AND_HERZEGOVINA => '387',
            self::BOTSWANA => '267',
            self::BRAZIL => '55',
            self::BRUNEI => '673',
            self::BULGARIA => '359',
            self::BURKINA_FASO => '226',
            self::BURUNDI => '257',
            self::CABO_VERDE => '238',
            self::CAMBODIA => '855',
            self::CAMEROON => '237',
            self::CANADA => '1',
            self::CENTRAL_AFRICAN_REPUBLIC => '236',
            self::CHAD => '235',
            self::CHILE => '56',
            self::CHINA => '86',
            self::COLOMBIA => '57',
            self::COMOROS => '269',
            self::CONGO_DEMOCRATIC_REPUBLIC => '243',
            self::CONGO_REPUBLIC => '242',
            self::COSTA_RICA => '506',
            self::CROATIA => '385',
            self::CUBA => '53',
            self::CYPRUS => '357',
            self::CZECH_REPUBLIC => '420',
            self::DENMARK => '45',
            self::DJIBOUTI => '253',
            self::DOMINICA => '1-767',
            self::DOMINICAN_REPUBLIC => '1-809',
            self::ECUADOR => '593',
            self::EGYPT => '20',
            self::EL_SALVADOR => '503',
            self::EQUATORIAL_GUINEA => '240',
            self::ERITREA => '291',
            self::ESTONIA => '372',
            self::ESWATINI => '268',
            self::ETHIOPIA => '251',
            self::FIJI => '679',
            self::FINLAND => '358',
            self::FRANCE => '33',
            self::GABON => '241',
            self::GAMBIA => '220',
            self::GEORGIA => '995',
            self::GERMANY => '49',
            self::GHANA => '233',
            self::GREECE => '30',
            self::GRENADA => '1-473',
            self::GUATEMALA => '502',
            self::GUINEA => '224',
            self::GUINEA_BISSAU => '245',
            self::GUYANA => '592',
            self::HAITI => '509',
            self::HONDURAS => '504',
            self::HUNGARY => '36',
            self::ICELAND => '354',
            self::INDIA => '91',
            self::INDONESIA => '62',
            self::IRAN => '98',
            self::IRAQ => '964',
            self::IRELAND => '353',
            self::ISRAEL => '972',
            self::ITALY => '39',
            self::JAMAICA => '1-876',
            self::JAPAN => '81',
            self::JORDAN => '962',
            self::KAZAKHSTAN => '7',
            self::KENYA => '254',
            self::KIRIBATI => '686',
            self::KOREA_NORTH => '850',
            self::KOREA_SOUTH => '82',
            self::KOSOVO => '383',
            self::KUWAIT => '965',
            self::KYRGYZSTAN => '996',
            self::LAOS => '856',
            self::LATVIA => '371',
            self::LEBANON => '961',
            self::LESOTHO => '266',
            self::LIBERIA => '231',
            self::LIBYA => '218',
            self::LIECHTENSTEIN => '423',
            self::LITHUANIA => '370',
            self::LUXEMBOURG => '352',
            self::MADAGASCAR => '261',
            self::MALAWI => '265',
            self::MALAYSIA => '60',
            self::MALDIVES => '960',
            self::MALI => '223',
            self::MALTA => '356',
            self::MARSHALL_ISLANDS => '692',
            self::MAURITANIA => '222',
            self::MAURITIUS => '230',
            self::MEXICO => '52',
            self::MICRONESIA => '691',
            self::MOLDOVA => '373',
            self::MONACO => '377',
            self::MONGOLIA => '976',
            self::MONTENEGRO => '382',
            self::MOROCCO => '212',
            self::MOZAMBIQUE => '258',
            self::MYANMAR => '95',
            self::NAMIBIA => '264',
            self::NAURU => '674',
            self::NEPAL => '977',
            self::NETHERLANDS => '31',
            self::NEW_ZEALAND => '64',
            self::NICARAGUA => '505',
            self::NIGER => '227',
            self::NIGERIA => '234',
            self::NORTH_MACEDONIA => '389',
            self::NORWAY => '47',
            self::OMAN => '968',
            self::PAKISTAN => '92',
            self::PALAU => '680',
            self::PALESTINE => '970',
            self::PANAMA => '507',
            self::PAPUA_NEW_GUINEA => '675',
            self::PARAGUAY => '595',
            self::PERU => '51',
            self::PHILIPPINES => '63',
            self::POLAND => '48',
            self::PORTUGAL => '351',
            self::QATAR => '974',
            self::ROMANIA => '40',
            self::RUSSIA => '7',
            self::RWANDA => '250',
            self::SAINT_KITTS_AND_NEVIS => '1-869',
            self::SAINT_LUCIA => '1-758',
            self::SAINT_VINCENT_AND_THE_GRENADINES => '1-784',
            self::SAMOA => '685',
            self::SAN_MARINO => '378',
            self::SAO_TOME_AND_PRINCIPE => '239',
            self::SAUDI_ARABIA => '966',
            self::SENEGAL => '221',
            self::SERBIA => '381',
            self::SEYCHELLES => '248',
            self::SIERRA_LEONE => '232',
            self::SINGAPORE => '65',
            self::SLOVAKIA => '421',
            self::SLOVENIA => '386',
            self::SOLOMON_ISLANDS => '677',
            self::SOMALIA => '252',
            self::SOUTH_AFRICA => '27',
            self::SOUTH_SUDAN => '211',
            self::SPAIN => '34',
            self::SRI_LANKA => '94',
            self::SUDAN => '249',
            self::SURINAME => '597',
            self::SWEDEN => '46',
            self::SWITZERLAND => '41',
            self::SYRIA => '963',
            self::TAIWAN => '886',
            self::TAJIKISTAN => '992',
            self::TANZANIA => '255',
            self::THAILAND => '66',
            self::TIMOR_LESTE => '670',
            self::TOGO => '228',
            self::TONGA => '676',
            self::TRINIDAD_AND_TOBAGO => '1-868',
            self::TUNISIA => '216',
            self::TURKEY => '90',
            self::TURKMENISTAN => '993',
            self::TUVALU => '688',
            self::UGANDA => '256',
            self::UKRAINE => '380',
            self::UNITED_ARAB_EMIRATES => '971',
            self::UNITED_KINGDOM => '44',
            self::UNITED_STATES => '1',
            self::URUGUAY => '598',
            self::UZBEKISTAN => '998',
            self::VANUATU => '678',
            self::VATICAN_CITY => '379',
            self::VENEZUELA => '58',
            self::VIETNAM => '84',
            self::YEMEN => '967',
            self::ZAMBIA => '260',
            self::ZIMBABWE => '263',
        };
    }

    /** @return string[] */
    public static function allPhonePrefixes(): array {
        return array_map(fn (self $country) => $country->phonePrefix(), self::cases());
    }

    // TODO: match for continent -> need continent enum
    // TODO: match for official languages -> need languages enum
    // TODO: match for official currencies -> need currencies enum
}
