<?php

namespace Talp1\LaravelRegistry\Enums;

use Talp1\LaravelRegistry\Enums\Contracts\CanBeCollected;
use Talp1\LaravelRegistry\Enums\Contracts\HasLabels;
use Talp1\LaravelRegistry\Enums\Contracts\HasRandom;
use Talp1\LaravelRegistry\Enums\Traits\CanBeCollected as CanBeCollectedTrait;
use Talp1\LaravelRegistry\Enums\Traits\ConvertsValueToLabel;
use Talp1\LaravelRegistry\Enums\Traits\HasRandom as HasRandomTrait;

/**
 * Enum containing all the world currencies and their ISO 4217 info ({@link https://en.wikipedia.org/wiki/ISO_4217}).
 *
 * Note that the list or its bindings may be incomplete or not up-to-date.
 * If you find an error or an inconsistency, please open an issue or a pull request at {@link https://github.com/Talpx1/laravel-registry}
 *
 * @implements CanBeCollected<string>
 * @implements HasRandom<string>
 */
enum Currencies: string implements CanBeCollected, HasLabels, HasRandom {
    /**
     * @use CanBeCollectedTrait<string>
     *     @use HasRandomTrait<string>
     */
    use CanBeCollectedTrait, ConvertsValueToLabel, HasRandomTrait;

    case AFGHANI = 'afghani';
    case ALBANIAN_LEK = 'albanian lek';
    case ALGERIAN_DINAR = 'algerian dinar';
    case EURO = 'euro';
    case ANGOLAN_KWANZA = 'angolan kwanza';
    case EAST_CARIBBEAN_DOLLAR = 'east caribbean dollar';
    case ARGENTINE_PESO = 'argentine peso';
    case ARMENIAN_DRAM = 'armenian dram';
    case AUSTRALIAN_DOLLAR = 'australian dollar';
    case AZERBAIJANI_MANAT = 'azerbaijani manat';
    case BAHAMIAN_DOLLAR = 'bahamian dollar';
    case BAHRAINI_DINAR = 'bahraini dinar';
    case BANGLADESHI_TAKA = 'bangladeshi taka';
    case BARBADIAN_DOLLAR = 'barbadian dollar';
    case BELARUSIAN_RUBLE = 'belarusian ruble';
    case BELGIAN_FRANC = 'belgian franc';
    case BELIZE_DOLLAR = 'belize dollar';
    case BHUTANESE_NGULTRUM = 'bhutanese ngultrum';
    case BOLIVIAN_BOLIVIANO = 'bolivian boliviano';
    case BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK = 'bosnia and herzegovina convertible mark';
    case BOTSWANA_PULA = 'botswana pula';
    case BRAZILIAN_REAL = 'brazilian real';
    case BRUNEIAN_DOLLAR = 'bruneian dollar';
    case BULGARIAN_LEV = 'bulgarian lev';
    case BURUNDIAN_FRANC = 'burundian franc';
    case CABO_VERDE_ESCUDO = 'cabo verde escudo';
    case CAMBODIAN_RIEL = 'cambodian riel';
    case CANADIAN_DOLLAR = 'canadian dollar';
    case CHILEAN_PESO = 'chilean peso';
    case CHINESE_YUAN = 'chinese yuan';
    case COLOMBIAN_PESO = 'colombian peso';
    case COMORIAN_FRANC = 'comorian franc';
    case CONGOLESE_FRANC = 'congolese franc';
    case COSTA_RICAN_COLON = 'costa rican colon';
    case CROATIAN_KUNA = 'croatian kuna';
    case CUBAN_PESO = 'cuban peso';
    case CYPRIOT_POUND = 'cypriot pound';
    case CZECH_KORUNA = 'czech koruna';
    case DANISH_KRONE = 'danish krone';
    case DJIBOUTIAN_FRANC = 'djiboutian franc';
    case DOMINICAN_PESO = 'dominican peso';
    case ECUADORIAN_SUCRE = 'ecuadorian sucre';
    case EGYPTIAN_POUND = 'egyptian pound';
    case SALVADORAN_COLON = 'salvadoran colon';
    case ERITREAN_NAKFA = 'eritrean nakfa';
    case ESTONIAN_KROON = 'estonian kroon';
    case ESWATINI_LILANGENI = 'eswatini lilangeni';
    case ETHIOPIAN_BIRR = 'ethiopian birr';
    case FIJIAN_DOLLAR = 'fijian dollar';
    case FINNISH_MARKKA = 'finnish markka';
    case FRENCH_FRANC = 'french franc';
    case GABONESE_FRANC = 'gabonese franc';
    case GAMBIAN_DALASI = 'gambian dalasi';
    case GEORGIAN_LARI = 'georgian lari';
    case GERMAN_MARK = 'german mark';
    case GHANAIAN_CEDI = 'ghanaian cedi';
    case GREEK_DRACHMA = 'greek drachma';
    case GRENADIAN_DOLLAR = 'grenadian dollar';
    case GUATEMALAN_QUETZAL = 'guatemalan quetzal';
    case GUINEAN_FRANC = 'guinean franc';
    case GUINEA_BISSAU_PESO = 'guinea bissau peso';
    case GUYANESE_DOLLAR = 'guyanese dollar';
    case HAITIAN_GOURDE = 'haitian gourde';
    case HONDURAN_LEMPIRA = 'honduran lempira';
    case HUNGARIAN_FORINT = 'hungarian forint';
    case ICELANDIC_KRONA = 'icelandic krona';
    case INDIAN_RUPEE = 'indian rupee';
    case INDONESIAN_RUPIAH = 'indonesian rupiah';
    case IRANIAN_RIAL = 'iranian rial';
    case IRAQI_DINAR = 'iraqi dinar';
    case IRISH_POUND = 'irish pound';
    case ISRAELI_SHEKEL = 'israeli shekel';
    case ITALIAN_LIRA = 'italian lira';
    case JAMAICAN_DOLLAR = 'jamaican dollar';
    case JAPANESE_YEN = 'japanese yen';
    case JORDANIAN_DINAR = 'jordanian dinar';
    case KAZAKHSTANI_TENGE = 'kazakhstani tenge';
    case KENYAN_SHILLING = 'kenyan shilling';
    case KIRIBATI_DOLLAR = 'kiribati dollar';
    case NORTH_KOREAN_WON = 'north korean won';
    case SOUTH_KOREAN_WON = 'south korean won';
    case KOSOVO_EURO = 'kosovo euro';
    case KUWAITI_DINAR = 'kuwaiti dinar';
    case KYRGYZSTANI_SOM = 'kyrgyzstani som';
    case LAO_KIP = 'lao kip';
    case LATVIAN_LATS = 'latvian lats';
    case LEBANESE_POUND = 'lebanese pound';
    case LESOTHO_LOTI = 'lesotho loti';
    case LIBERIAN_DOLLAR = 'liberian dollar';
    case LIBYAN_DINAR = 'libyan dinar';
    case LIECHTENSTEIN_FRANC = 'liechtenstein franc';
    case LITHUANIAN_LITAS = 'lithuanian litas';
    case LUXEMBOURG_FRANC = 'luxembourg franc';
    case MALAGASY_ARIARY = 'malagasy ariary';
    case MALAWIAN_KWACHA = 'malawian kwacha';
    case MALAYSIAN_RINGGIT = 'malaysian ringgit';
    case MALDIVIAN_RUFIYAA = 'maldivian rufiyaa';
    case MALIAN_FRANC = 'malian franc';
    case MALTESE_LIRA = 'maltese lira';
    case MARSHALLESE_DOLLAR = 'marshallese dollar';
    case MAURITANIAN_OUGUIYA = 'mauritanian ouguiya';
    case MAURITIAN_RUPEE = 'mauritian rupee';
    case MEXICAN_PESO = 'mexican peso';
    case MICRONESIAN_DOLLAR = 'micronesian dollar';
    case MOLDOVAN_LEU = 'moldovan leu';
    case MONACO_FRANC = 'monaco franc';
    case MONGOLIAN_TUGRIK = 'mongolian tugrik';
    case MONTENEGRIN_EURO = 'montenegrin euro';
    case MOROCCAN_DIRHAM = 'moroccan dirham';
    case MOZAMBICAN_METICAL = 'mozambican metical';
    case MYANMA_KYAT = 'myanma kyat';
    case NAMIBIAN_DOLLAR = 'namibian dollar';
    case NAURUAN_DOLLAR = 'nauruan dollar';
    case NEPALESE_RUPEE = 'nepalese rupee';
    case DUTCH_GUILDER = 'dutch guilder';
    case NEW_ZEALAND_DOLLAR = 'new zealand dollar';
    case NICARAGUAN_CORDOBA = 'nicaraguan cordoba';
    case NIGERIAN_NAIRA = 'nigerian naira';
    case MACEDONIAN_DENAR = 'macedonian denar';
    case NORWEGIAN_KRONE = 'norwegian krone';
    case OMANI_RIAL = 'omani rial';
    case PAKISTANI_RUPEE = 'pakistani rupee';
    case PALAUAN_DOLLAR = 'palauan dollar';
    case PALESTINIAN_POUND = 'palestinian pound';
    case PANAMANIAN_BALBOA = 'panamanian balboa';
    case PAPUA_NEW_GUINEAN_KINA = 'papua new guinean kina';
    case PARAGUAYAN_GUARANI = 'paraguayan guarani';
    case PERUVIAN_SOL = 'peruvian sol';
    case PHILIPPINE_PESO = 'philippine peso';
    case POLISH_ZLOTY = 'polish zloty';
    case PORTUGUESE_ESCUDO = 'portuguese escudo';
    case QATARI_RIAL = 'qatari rial';
    case ROMANIAN_LEU = 'romanian leu';
    case RUSSIAN_RUBLE = 'russian ruble';
    case RWANDAN_FRANC = 'rwandan franc';
    case SAINT_KITTS_AND_NEVIS_DOLLAR = 'saint kitts and nevis dollar';
    case SAINT_LUCIA_DOLLAR = 'saint lucia dollar';
    case SAINT_VINCENT_AND_THE_GRENADINES_DOLLAR = 'saint vincent and the grenadines dollar';
    case SAMOAN_TALA = 'samoan tala';
    case SAN_MARINO_LIRA = 'san marino lira';
    case SAO_TOME_AND_PRINCIPE_DOBRA = 'sao tome and principe dobra';
    case SAUDI_RIYAL = 'saudi riyal';
    case SENEGALESE_FRANC = 'senegalese franc';
    case SERBIAN_DINAR = 'serbian dinar';
    case SEYCHELLOIS_RUPEE = 'seychellois rupee';
    case SIERRA_LEONEAN_LEONE = 'sierra leonean leone';
    case SINGAPORE_DOLLAR = 'singapore dollar';
    case SLOVAK_KORUNA = 'slovak koruna';
    case SLOVENIAN_TOLAR = 'slovenian tolar';
    case SOLOMON_ISLANDS_DOLLAR = 'solomon islands dollar';
    case SOMALI_SHILLING = 'somali shilling';
    case SOUTH_AFRICAN_RAND = 'south african rand';
    case SOUTH_SUDANESE_POUND = 'south sudanese pound';
    case SPANISH_PESETA = 'spanish peseta';
    case SRI_LANKAN_RUPEE = 'sri lankan rupee';
    case SUDANESE_POUND = 'sudanese pound';
    case SURINAMESE_DOLLAR = 'surinamese dollar';
    case SWEDISH_KRONA = 'swedish krona';
    case SWISS_FRANC = 'swiss franc';
    case SYRIAN_POUND = 'syrian pound';
    case TAIWANESE_DOLLAR = 'taiwanese dollar';
    case TAJIKISTANI_SOMONI = 'tajikistani somoni';
    case TANZANIAN_SHILLING = 'tanzanian shilling';
    case THAI_BAHT = 'thai baht';
    case TIMORESE_ESCUDO = 'timorese escudo';
    case TOGOLESE_FRANC = 'togolese franc';
    case TONGAN_PAANGA = 'tongan paanga';
    case TRINIDAD_AND_TOBAGO_DOLLAR = 'trinidad and tobago dollar';
    case TUNISIAN_DINAR = 'tunisian dinar';
    case TURKISH_LIRA = 'turkish lira';
    case TURKMENISTANI_MANAT = 'turkmenistani manat';
    case TUVALUAN_DOLLAR = 'tuvaluan dollar';
    case UGANDAN_SHILLING = 'ugandan shilling';
    case UKRAINIAN_HRYVNIA = 'ukrainian hryvnia';
    case UAE_DIRHAM = 'uae dirham';
    case BRITISH_POUND = 'british pound';
    case US_DOLLAR = 'us dollar';
    case URUGUAYAN_PESO = 'uruguayan peso';
    case UZBEKISTANI_SOM = 'uzbekistani som';
    case VANUATU_VATU = 'vanuatu vatu';
    case VATICAN_LIRA = 'vatican lira';
    case VENEZUELAN_BOLIVAR = 'venezuelan bolivar';
    case VIETNAMESE_DONG = 'vietnamese dong';
    case YEMENI_RIAL = 'yemeni rial';
    case ZAMBIAN_KWACHA = 'zambian kwacha';
    case ZIMBABWEAN_DOLLAR = 'zimbabwean dollar';
    case CFA_FRANC_BCEAO = 'cfa franc bceao';
    case CFA_FRANC_BEAC = 'cfa franc beac';
    case CFP_FRANC = 'cfp franc';
    case NETHERLANDS_ANTILLEAN_GUILDER = 'netherlands antillean guilder';
    case ARUBAN_FLORIN = 'aruban florin';
    case HONG_KONG_DOLLAR = 'hong kong dollar';
    case MACANESE_PATACA = 'macanese pataca';

    /**
     * Returns the symbol or abbreviation (when a symbol is not available) of the currency.
     *
     * Note that the returned string may contain unicode characters.
     *
     * @link https://en.wikipedia.org/wiki/Currency_symbol, https://en.wikipedia.org/wiki/List_of_circulating_currencies
     */
    public function symbolOrAbbreviation(): string {
        return match ($this) {
            self::AFGHANI => '؋',
            self::ALBANIAN_LEK => 'L',
            self::ALGERIAN_DINAR => 'د.ج',
            self::EURO => '€',
            self::ANGOLAN_KWANZA => 'Kz',
            self::EAST_CARIBBEAN_DOLLAR => 'EC$',
            self::ARGENTINE_PESO => '$',
            self::ARMENIAN_DRAM => '֏',
            self::AUSTRALIAN_DOLLAR => '$',
            self::AZERBAIJANI_MANAT => '₼',
            self::BAHAMIAN_DOLLAR => '$',
            self::BAHRAINI_DINAR => '.د.ب',
            self::BANGLADESHI_TAKA => '৳',
            self::BARBADIAN_DOLLAR => '$',
            self::BELARUSIAN_RUBLE => 'Br',
            self::BELGIAN_FRANC => 'BEF',
            self::BELIZE_DOLLAR => '$',
            self::BHUTANESE_NGULTRUM => 'Nu',
            self::BOLIVIAN_BOLIVIANO => 'Bs',
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => 'KM',
            self::BOTSWANA_PULA => 'P',
            self::BRAZILIAN_REAL => 'R$',
            self::BRUNEIAN_DOLLAR => '$',
            self::BULGARIAN_LEV => 'лв',
            self::BURUNDIAN_FRANC => 'FBu',
            self::CABO_VERDE_ESCUDO => 'CVE',
            self::CAMBODIAN_RIEL => '៛',
            self::CANADIAN_DOLLAR => '$',
            self::CHILEAN_PESO => '$',
            self::CHINESE_YUAN => '¥',
            self::COLOMBIAN_PESO => '$',
            self::COMORIAN_FRANC => 'FC',
            self::CONGOLESE_FRANC => 'FC',
            self::COSTA_RICAN_COLON => '₡',
            self::CROATIAN_KUNA => 'kn',
            self::CUBAN_PESO => '$',
            self::CYPRIOT_POUND => '£',
            self::CZECH_KORUNA => 'Kč',
            self::DANISH_KRONE => 'kr',
            self::DJIBOUTIAN_FRANC => 'Fdj',
            self::DOMINICAN_PESO => '$',
            self::ECUADORIAN_SUCRE => 'S/',
            self::EGYPTIAN_POUND => 'LE',
            self::SALVADORAN_COLON => '₡',
            self::ERITREAN_NAKFA => 'Nfk',
            self::ESTONIAN_KROON => 'EEK',
            self::ESWATINI_LILANGENI => 'E',
            self::ETHIOPIAN_BIRR => 'Br',
            self::FIJIAN_DOLLAR => '$',
            self::FINNISH_MARKKA => 'FIM',
            self::FRENCH_FRANC => 'FRF',
            self::GABONESE_FRANC => 'CFA',
            self::GAMBIAN_DALASI => 'D',
            self::GEORGIAN_LARI => '₾',
            self::GERMAN_MARK => 'DEM',
            self::GHANAIAN_CEDI => '₵',
            self::GREEK_DRACHMA => '₯',
            self::GRENADIAN_DOLLAR => '$',
            self::GUATEMALAN_QUETZAL => 'Q',
            self::GUINEAN_FRANC => 'FG',
            self::GUINEA_BISSAU_PESO => 'GWP',
            self::GUYANESE_DOLLAR => '$',
            self::HAITIAN_GOURDE => 'G',
            self::HONDURAN_LEMPIRA => 'L',
            self::HUNGARIAN_FORINT => 'Ft',
            self::ICELANDIC_KRONA => 'kr',
            self::INDIAN_RUPEE => '₹',
            self::INDONESIAN_RUPIAH => 'Rp',
            self::IRANIAN_RIAL => '﷼',
            self::IRAQI_DINAR => 'ع.د',
            self::IRISH_POUND => '£',
            self::ISRAELI_SHEKEL => '₪',
            self::ITALIAN_LIRA => '₤',
            self::JAMAICAN_DOLLAR => '$',
            self::JAPANESE_YEN => '¥',
            self::JORDANIAN_DINAR => 'د.ا',
            self::KAZAKHSTANI_TENGE => '₸',
            self::KENYAN_SHILLING => 'KSh',
            self::KIRIBATI_DOLLAR => '$',
            self::NORTH_KOREAN_WON => '₩',
            self::SOUTH_KOREAN_WON => '₩',
            self::KOSOVO_EURO => '€',
            self::KUWAITI_DINAR => 'د.ك',
            self::KYRGYZSTANI_SOM => 'лв',
            self::LAO_KIP => '₭',
            self::LATVIAN_LATS => 'Ls',
            self::LEBANESE_POUND => 'ل.ل',
            self::LESOTHO_LOTI => 'L',
            self::LIBERIAN_DOLLAR => '$',
            self::LIBYAN_DINAR => 'ل.د',
            self::LIECHTENSTEIN_FRANC => 'CHF',
            self::LITHUANIAN_LITAS => 'Lt',
            self::LUXEMBOURG_FRANC => 'LUF',
            self::MALAGASY_ARIARY => 'Ar',
            self::MALAWIAN_KWACHA => 'MK',
            self::MALAYSIAN_RINGGIT => 'RM',
            self::MALDIVIAN_RUFIYAA => 'Rf',
            self::MALIAN_FRANC => 'CFA',
            self::MALTESE_LIRA => '₤',
            self::MARSHALLESE_DOLLAR => '$',
            self::MAURITANIAN_OUGUIYA => 'UM',
            self::MAURITIAN_RUPEE => '₨',
            self::MEXICAN_PESO => '$',
            self::MICRONESIAN_DOLLAR => '$',
            self::MOLDOVAN_LEU => 'L',
            self::MONACO_FRANC => 'MCF',
            self::MONGOLIAN_TUGRIK => '₮',
            self::MONTENEGRIN_EURO => '€',
            self::MOROCCAN_DIRHAM => 'د.م.',
            self::MOZAMBICAN_METICAL => 'MT',
            self::MYANMA_KYAT => 'K',
            self::NAMIBIAN_DOLLAR => '$',
            self::NAURUAN_DOLLAR => '$',
            self::NEPALESE_RUPEE => '₨',
            self::DUTCH_GUILDER => 'ƒ',
            self::NEW_ZEALAND_DOLLAR => '$',
            self::NICARAGUAN_CORDOBA => 'C$',
            self::NIGERIAN_NAIRA => '₦',
            self::MACEDONIAN_DENAR => 'ден',
            self::NORWEGIAN_KRONE => 'kr',
            self::OMANI_RIAL => 'ر.ع.',
            self::PAKISTANI_RUPEE => '₨',
            self::PALAUAN_DOLLAR => '$',
            self::PALESTINIAN_POUND => '£',
            self::PANAMANIAN_BALBOA => 'B/.',
            self::PAPUA_NEW_GUINEAN_KINA => 'K',
            self::PARAGUAYAN_GUARANI => '₲',
            self::PERUVIAN_SOL => 'S/',
            self::PHILIPPINE_PESO => '₱',
            self::POLISH_ZLOTY => 'zł',
            self::PORTUGUESE_ESCUDO => 'Esc',
            self::QATARI_RIAL => 'ر.ق',
            self::ROMANIAN_LEU => 'lei',
            self::RUSSIAN_RUBLE => '₽',
            self::RWANDAN_FRANC => 'FRw',
            self::SAINT_KITTS_AND_NEVIS_DOLLAR => '$',
            self::SAINT_LUCIA_DOLLAR => '$',
            self::SAINT_VINCENT_AND_THE_GRENADINES_DOLLAR => '$',
            self::SAMOAN_TALA => 'WS$',
            self::SAN_MARINO_LIRA => '₤',
            self::SAO_TOME_AND_PRINCIPE_DOBRA => 'Db',
            self::SAUDI_RIYAL => 'ر.س',
            self::SENEGALESE_FRANC => 'CFA',
            self::SERBIAN_DINAR => 'дин.',
            self::SEYCHELLOIS_RUPEE => '₨',
            self::SIERRA_LEONEAN_LEONE => 'Le',
            self::SINGAPORE_DOLLAR => '$',
            self::SLOVAK_KORUNA => 'Sk',
            self::SLOVENIAN_TOLAR => 'SIT',
            self::SOLOMON_ISLANDS_DOLLAR => '$',
            self::SOMALI_SHILLING => 'Sh.So.',
            self::SOUTH_AFRICAN_RAND => 'R',
            self::SOUTH_SUDANESE_POUND => '£',
            self::SPANISH_PESETA => '₧',
            self::SRI_LANKAN_RUPEE => 'Rs',
            self::SUDANESE_POUND => 'ج.س.',
            self::SURINAMESE_DOLLAR => '$',
            self::SWEDISH_KRONA => 'kr',
            self::SWISS_FRANC => 'CHF',
            self::SYRIAN_POUND => '£',
            self::TAIWANESE_DOLLAR => 'NT$',
            self::TAJIKISTANI_SOMONI => 'ЅМ',
            self::TANZANIAN_SHILLING => 'TSh',
            self::THAI_BAHT => '฿',
            self::TIMORESE_ESCUDO => 'Esc',
            self::TOGOLESE_FRANC => 'CFA',
            self::TONGAN_PAANGA => 'T$',
            self::TRINIDAD_AND_TOBAGO_DOLLAR => '$',
            self::TUNISIAN_DINAR => 'د.ت',
            self::TURKISH_LIRA => '₺',
            self::TURKMENISTANI_MANAT => 'm',
            self::TUVALUAN_DOLLAR => '$',
            self::UGANDAN_SHILLING => 'USh',
            self::UKRAINIAN_HRYVNIA => '₴',
            self::UAE_DIRHAM => 'د.إ',
            self::BRITISH_POUND => '£',
            self::US_DOLLAR => '$',
            self::URUGUAYAN_PESO => '$U',
            self::UZBEKISTANI_SOM => 'лв',
            self::VANUATU_VATU => 'VT',
            self::VATICAN_LIRA => '₤',
            self::VENEZUELAN_BOLIVAR => 'Bs',
            self::VIETNAMESE_DONG => '₫',
            self::YEMENI_RIAL => '﷼',
            self::ZAMBIAN_KWACHA => 'K',
            self::ZIMBABWEAN_DOLLAR => '$',
            self::CFA_FRANC_BCEAO => 'CFA',
            self::CFA_FRANC_BEAC => 'CFA',
            self::CFP_FRANC => 'CFP',
            self::NETHERLANDS_ANTILLEAN_GUILDER => 'NAƒ',
            self::ARUBAN_FLORIN => 'Afl.',
            self::HONG_KONG_DOLLAR => 'HK$',
            self::MACANESE_PATACA => 'MOP$',
        };
    }

    /**
     * Returns the ISO 4217 code of the currency or `null` if the currency has no ISO 4217 code associated.
     *
     * The ISO 4217 code is composed of three uppercase letters.
     *
     * @link https://en.wikipedia.org/wiki/ISO_4217
     */
    public function iso4217Code(): ?string {
        return match ($this) {
            self::AFGHANI => 'AFN',
            self::ALBANIAN_LEK => 'ALL',
            self::ALGERIAN_DINAR => 'DZD',
            self::EURO => 'EUR',
            self::ANGOLAN_KWANZA => 'AOA',
            self::EAST_CARIBBEAN_DOLLAR => 'XCD',
            self::ARGENTINE_PESO => 'ARS',
            self::ARMENIAN_DRAM => 'AMD',
            self::AUSTRALIAN_DOLLAR => 'AUD',
            self::AZERBAIJANI_MANAT => 'AZN',
            self::BAHAMIAN_DOLLAR => 'BSD',
            self::BAHRAINI_DINAR => 'BHD',
            self::BANGLADESHI_TAKA => 'BDT',
            self::BARBADIAN_DOLLAR => 'BBD',
            self::BELARUSIAN_RUBLE => 'BYN',
            self::BELIZE_DOLLAR => 'BZD',
            self::BHUTANESE_NGULTRUM => 'BTN',
            self::BOLIVIAN_BOLIVIANO => 'BOB',
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => 'BAM',
            self::BOTSWANA_PULA => 'BWP',
            self::BRAZILIAN_REAL => 'BRL',
            self::BRUNEIAN_DOLLAR => 'BND',
            self::BULGARIAN_LEV => 'BGN',
            self::BURUNDIAN_FRANC => 'BIF',
            self::CABO_VERDE_ESCUDO => 'CVE',
            self::CAMBODIAN_RIEL => 'KHR',
            self::CANADIAN_DOLLAR => 'CAD',
            self::CHILEAN_PESO => 'CLP',
            self::CHINESE_YUAN => 'CNY',
            self::COLOMBIAN_PESO => 'COP',
            self::COMORIAN_FRANC => 'KMF',
            self::CONGOLESE_FRANC => 'CDF',
            self::COSTA_RICAN_COLON => 'CRC',
            self::CROATIAN_KUNA => 'HRK',
            self::CUBAN_PESO => 'CUP',
            self::CZECH_KORUNA => 'CZK',
            self::DANISH_KRONE => 'DKK',
            self::DJIBOUTIAN_FRANC => 'DJF',
            self::DOMINICAN_PESO => 'DOP',
            self::EGYPTIAN_POUND => 'EGP',
            self::SALVADORAN_COLON => 'SVC',
            self::ERITREAN_NAKFA => 'ERN',
            self::ESWATINI_LILANGENI => 'SZL',
            self::ETHIOPIAN_BIRR => 'ETB',
            self::FIJIAN_DOLLAR => 'FJD',
            self::GAMBIAN_DALASI => 'GMD',
            self::GEORGIAN_LARI => 'GEL',
            self::GHANAIAN_CEDI => 'GHS',
            self::GUATEMALAN_QUETZAL => 'GTQ',
            self::GUINEAN_FRANC => 'GNF',
            self::GUYANESE_DOLLAR => 'GYD',
            self::HAITIAN_GOURDE => 'HTG',
            self::HONDURAN_LEMPIRA => 'HNL',
            self::HUNGARIAN_FORINT => 'HUF',
            self::ICELANDIC_KRONA => 'ISK',
            self::INDIAN_RUPEE => 'INR',
            self::INDONESIAN_RUPIAH => 'IDR',
            self::IRANIAN_RIAL => 'IRR',
            self::IRAQI_DINAR => 'IQD',
            self::ISRAELI_SHEKEL => 'ILS',
            self::JAMAICAN_DOLLAR => 'JMD',
            self::JAPANESE_YEN => 'JPY',
            self::JORDANIAN_DINAR => 'JOD',
            self::KAZAKHSTANI_TENGE => 'KZT',
            self::KENYAN_SHILLING => 'KES',
            self::KIRIBATI_DOLLAR => 'AUD',
            self::NORTH_KOREAN_WON => 'KPW',
            self::SOUTH_KOREAN_WON => 'KRW',
            self::KUWAITI_DINAR => 'KWD',
            self::KYRGYZSTANI_SOM => 'KGS',
            self::LAO_KIP => 'LAK',
            self::LATVIAN_LATS => 'LVL',
            self::LEBANESE_POUND => 'LBP',
            self::LESOTHO_LOTI => 'LSL',
            self::LIBERIAN_DOLLAR => 'LRD',
            self::LIBYAN_DINAR => 'LYD',
            self::LITHUANIAN_LITAS => 'LTL',
            self::MALAGASY_ARIARY => 'MGA',
            self::MALAWIAN_KWACHA => 'MWK',
            self::MALAYSIAN_RINGGIT => 'MYR',
            self::MALDIVIAN_RUFIYAA => 'MVR',
            self::MAURITANIAN_OUGUIYA => 'MRU',
            self::MAURITIAN_RUPEE => 'MUR',
            self::MEXICAN_PESO => 'MXN',
            self::MOLDOVAN_LEU => 'MDL',
            self::MONGOLIAN_TUGRIK => 'MNT',
            self::MOROCCAN_DIRHAM => 'MAD',
            self::MOZAMBICAN_METICAL => 'MZN',
            self::MYANMA_KYAT => 'MMK',
            self::NAMIBIAN_DOLLAR => 'NAD',
            self::NEPALESE_RUPEE => 'NPR',
            self::NEW_ZEALAND_DOLLAR => 'NZD',
            self::NICARAGUAN_CORDOBA => 'NIO',
            self::NIGERIAN_NAIRA => 'NGN',
            self::MACEDONIAN_DENAR => 'MKD',
            self::NORWEGIAN_KRONE => 'NOK',
            self::OMANI_RIAL => 'OMR',
            self::PAKISTANI_RUPEE => 'PKR',
            self::PANAMANIAN_BALBOA => 'PAB',
            self::PAPUA_NEW_GUINEAN_KINA => 'PGK',
            self::PARAGUAYAN_GUARANI => 'PYG',
            self::PERUVIAN_SOL => 'PEN',
            self::PHILIPPINE_PESO => 'PHP',
            self::POLISH_ZLOTY => 'PLN',
            self::QATARI_RIAL => 'QAR',
            self::ROMANIAN_LEU => 'RON',
            self::RUSSIAN_RUBLE => 'RUB',
            self::RWANDAN_FRANC => 'RWF',
            self::SAUDI_RIYAL => 'SAR',
            self::SERBIAN_DINAR => 'RSD',
            self::SEYCHELLOIS_RUPEE => 'SCR',
            self::SIERRA_LEONEAN_LEONE => 'SLL',
            self::SINGAPORE_DOLLAR => 'SGD',
            self::SOLOMON_ISLANDS_DOLLAR => 'SBD',
            self::SOMALI_SHILLING => 'SOS',
            self::SOUTH_AFRICAN_RAND => 'ZAR',
            self::SOUTH_SUDANESE_POUND => 'SSP',
            self::SRI_LANKAN_RUPEE => 'LKR',
            self::SUDANESE_POUND => 'SDG',
            self::SURINAMESE_DOLLAR => 'SRD',
            self::SWEDISH_KRONA => 'SEK',
            self::SWISS_FRANC => 'CHF',
            self::SYRIAN_POUND => 'SYP',
            self::TAIWANESE_DOLLAR => 'TWD',
            self::TAJIKISTANI_SOMONI => 'TJS',
            self::TANZANIAN_SHILLING => 'TZS',
            self::THAI_BAHT => 'THB',
            self::TONGAN_PAANGA => 'TOP',
            self::TRINIDAD_AND_TOBAGO_DOLLAR => 'TTD',
            self::TUNISIAN_DINAR => 'TND',
            self::TURKISH_LIRA => 'TRY',
            self::TURKMENISTANI_MANAT => 'TMT',
            self::UGANDAN_SHILLING => 'UGX',
            self::UKRAINIAN_HRYVNIA => 'UAH',
            self::UAE_DIRHAM => 'AED',
            self::BRITISH_POUND => 'GBP',
            self::US_DOLLAR => 'USD',
            self::URUGUAYAN_PESO => 'UYU',
            self::UZBEKISTANI_SOM => 'UZS',
            self::VANUATU_VATU => 'VUV',
            self::VENEZUELAN_BOLIVAR => 'VES',
            self::VIETNAMESE_DONG => 'VND',
            self::YEMENI_RIAL => 'YER',
            self::ZAMBIAN_KWACHA => 'ZMW',
            self::ZIMBABWEAN_DOLLAR => 'ZWL',
            self::CFA_FRANC_BCEAO => 'XOF',
            self::CFA_FRANC_BEAC => 'XAF',
            self::CFP_FRANC => 'XPF',
            self::NETHERLANDS_ANTILLEAN_GUILDER => 'ANG',
            self::ARUBAN_FLORIN => 'AWG',
            self::HONG_KONG_DOLLAR => 'HKD',
            self::MACANESE_PATACA => 'MOP',
            default => null,
        };
    }

    /**
     * Returns the ISO 4217 number of the currency or `null` if the currency has no ISO 4217 number associated.
     *
     * The ISO 4217 number is composed of three numbers and may start with a `0`, hence why it's returned as string.
     *
     * @link https://en.wikipedia.org/wiki/ISO_4217
     */
    public function iso4217Number(): ?string {
        return match ($this) {
            self::AFGHANI => '971',
            self::ALBANIAN_LEK => '008',
            self::ALGERIAN_DINAR => '012',
            self::EURO => '978',
            self::ANGOLAN_KWANZA => '973',
            self::EAST_CARIBBEAN_DOLLAR => '951',
            self::ARGENTINE_PESO => '032',
            self::ARMENIAN_DRAM => '051',
            self::AUSTRALIAN_DOLLAR => '036',
            self::AZERBAIJANI_MANAT => '944',
            self::BAHAMIAN_DOLLAR => '044',
            self::BAHRAINI_DINAR => '048',
            self::BANGLADESHI_TAKA => '050',
            self::BARBADIAN_DOLLAR => '052',
            self::BELARUSIAN_RUBLE => '933',
            self::BELIZE_DOLLAR => '084',
            self::BHUTANESE_NGULTRUM => '064',
            self::BOLIVIAN_BOLIVIANO => '068',
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => '977',
            self::BOTSWANA_PULA => '072',
            self::BRAZILIAN_REAL => '986',
            self::BRUNEIAN_DOLLAR => '096',
            self::BULGARIAN_LEV => '975',
            self::BURUNDIAN_FRANC => '108',
            self::CABO_VERDE_ESCUDO => '132',
            self::CAMBODIAN_RIEL => '116',
            self::CANADIAN_DOLLAR => '124',
            self::CHILEAN_PESO => '152',
            self::CHINESE_YUAN => '156',
            self::COLOMBIAN_PESO => '170',
            self::COMORIAN_FRANC => '174',
            self::CONGOLESE_FRANC => '976',
            self::COSTA_RICAN_COLON => '188',
            self::CROATIAN_KUNA => '191',
            self::CUBAN_PESO => '192',
            self::CZECH_KORUNA => '203',
            self::DANISH_KRONE => '208',
            self::DJIBOUTIAN_FRANC => '262',
            self::DOMINICAN_PESO => '214',
            self::EGYPTIAN_POUND => '818',
            self::SALVADORAN_COLON => '222',
            self::ERITREAN_NAKFA => '232',
            self::ESWATINI_LILANGENI => '748',
            self::ETHIOPIAN_BIRR => '230',
            self::FIJIAN_DOLLAR => '242',
            self::GAMBIAN_DALASI => '270',
            self::GEORGIAN_LARI => '981',
            self::GHANAIAN_CEDI => '936',
            self::GRENADIAN_DOLLAR => '951',
            self::GUATEMALAN_QUETZAL => '320',
            self::GUINEAN_FRANC => '324',
            self::GUYANESE_DOLLAR => '328',
            self::HAITIAN_GOURDE => '332',
            self::HONDURAN_LEMPIRA => '340',
            self::HUNGARIAN_FORINT => '348',
            self::ICELANDIC_KRONA => '352',
            self::INDIAN_RUPEE => '356',
            self::INDONESIAN_RUPIAH => '360',
            self::IRANIAN_RIAL => '364',
            self::IRAQI_DINAR => '368',
            self::ISRAELI_SHEKEL => '376',
            self::JAMAICAN_DOLLAR => '388',
            self::JAPANESE_YEN => '392',
            self::JORDANIAN_DINAR => '400',
            self::KAZAKHSTANI_TENGE => '398',
            self::KENYAN_SHILLING => '404',
            self::KIRIBATI_DOLLAR => '036',
            self::NORTH_KOREAN_WON => '408',
            self::SOUTH_KOREAN_WON => '410',
            self::KUWAITI_DINAR => '414',
            self::KYRGYZSTANI_SOM => '417',
            self::LAO_KIP => '418',
            self::LATVIAN_LATS => '428',
            self::LEBANESE_POUND => '422',
            self::LESOTHO_LOTI => '426',
            self::LIBERIAN_DOLLAR => '430',
            self::LIBYAN_DINAR => '434',
            self::LITHUANIAN_LITAS => '440',
            self::MALAGASY_ARIARY => '969',
            self::MALAWIAN_KWACHA => '454',
            self::MALAYSIAN_RINGGIT => '458',
            self::MALDIVIAN_RUFIYAA => '462',
            self::MAURITANIAN_OUGUIYA => '929',
            self::MAURITIAN_RUPEE => '480',
            self::MEXICAN_PESO => '484',
            self::MOLDOVAN_LEU => '498',
            self::MONGOLIAN_TUGRIK => '496',
            self::MOROCCAN_DIRHAM => '504',
            self::MOZAMBICAN_METICAL => '943',
            self::MYANMA_KYAT => '104',
            self::NAMIBIAN_DOLLAR => '516',
            self::NEPALESE_RUPEE => '524',
            self::NEW_ZEALAND_DOLLAR => '554',
            self::NICARAGUAN_CORDOBA => '558',
            self::NIGERIAN_NAIRA => '566',
            self::MACEDONIAN_DENAR => '807',
            self::NORWEGIAN_KRONE => '578',
            self::OMANI_RIAL => '512',
            self::PAKISTANI_RUPEE => '586',
            self::PANAMANIAN_BALBOA => '590',
            self::PAPUA_NEW_GUINEAN_KINA => '598',
            self::PARAGUAYAN_GUARANI => '600',
            self::PERUVIAN_SOL => '604',
            self::PHILIPPINE_PESO => '608',
            self::POLISH_ZLOTY => '985',
            self::QATARI_RIAL => '634',
            self::ROMANIAN_LEU => '946',
            self::RUSSIAN_RUBLE => '643',
            self::RWANDAN_FRANC => '646',
            self::SAUDI_RIYAL => '682',
            self::SERBIAN_DINAR => '941',
            self::SEYCHELLOIS_RUPEE => '690',
            self::SIERRA_LEONEAN_LEONE => '694',
            self::SINGAPORE_DOLLAR => '702',
            self::SOLOMON_ISLANDS_DOLLAR => '090',
            self::SOMALI_SHILLING => '706',
            self::SOUTH_AFRICAN_RAND => '710',
            self::SOUTH_SUDANESE_POUND => '728',
            self::SRI_LANKAN_RUPEE => '144',
            self::SUDANESE_POUND => '938',
            self::SURINAMESE_DOLLAR => '968',
            self::SWEDISH_KRONA => '752',
            self::SWISS_FRANC => '756',
            self::SYRIAN_POUND => '760',
            self::TAIWANESE_DOLLAR => '901',
            self::TAJIKISTANI_SOMONI => '972',
            self::TANZANIAN_SHILLING => '834',
            self::THAI_BAHT => '764',
            self::TONGAN_PAANGA => '776',
            self::TRINIDAD_AND_TOBAGO_DOLLAR => '780',
            self::TUNISIAN_DINAR => '788',
            self::TURKISH_LIRA => '949',
            self::TURKMENISTANI_MANAT => '934',
            self::UGANDAN_SHILLING => '800',
            self::UKRAINIAN_HRYVNIA => '980',
            self::UAE_DIRHAM => '784',
            self::BRITISH_POUND => '826',
            self::US_DOLLAR => '840',
            self::URUGUAYAN_PESO => '858',
            self::UZBEKISTANI_SOM => '860',
            self::VANUATU_VATU => '548',
            self::VENEZUELAN_BOLIVAR => '928',
            self::VIETNAMESE_DONG => '704',
            self::YEMENI_RIAL => '886',
            self::ZAMBIAN_KWACHA => '967',
            self::ZIMBABWEAN_DOLLAR => '932',
            self::CFA_FRANC_BCEAO => '952',
            self::CFA_FRANC_BEAC => '950',
            self::CFP_FRANC => '953',
            self::NETHERLANDS_ANTILLEAN_GUILDER => '532',
            self::ARUBAN_FLORIN => '533',
            self::HONG_KONG_DOLLAR => '344',
            self::MACANESE_PATACA => '446',
            default => null,
        };
    }

    /**
     * Returns the number of decimal digits of the currency according to the ISO 4217 standard
     * or `null` if the currency is not included in the ISO 4217 standard.
     *
     * @link https://en.wikipedia.org/wiki/ISO_4217
     */
    public function iso4217DecimalDigits(): ?int {
        return match ($this) {
            self::AFGHANI => 2,
            self::ALBANIAN_LEK => 2,
            self::ALGERIAN_DINAR => 2,
            self::EURO => 2,
            self::ANGOLAN_KWANZA => 2,
            self::EAST_CARIBBEAN_DOLLAR => 2,
            self::ARGENTINE_PESO => 2,
            self::ARMENIAN_DRAM => 2,
            self::AUSTRALIAN_DOLLAR => 2,
            self::AZERBAIJANI_MANAT => 2,
            self::BAHAMIAN_DOLLAR => 2,
            self::BAHRAINI_DINAR => 3,
            self::BANGLADESHI_TAKA => 2,
            self::BARBADIAN_DOLLAR => 2,
            self::BELARUSIAN_RUBLE => 2,
            self::BELIZE_DOLLAR => 2,
            self::BHUTANESE_NGULTRUM => 2,
            self::BOLIVIAN_BOLIVIANO => 2,
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => 2,
            self::BOTSWANA_PULA => 2,
            self::BRAZILIAN_REAL => 2,
            self::BRUNEIAN_DOLLAR => 2,
            self::BULGARIAN_LEV => 2,
            self::BURUNDIAN_FRANC => 0,
            self::CABO_VERDE_ESCUDO => 2,
            self::CAMBODIAN_RIEL => 2,
            self::CANADIAN_DOLLAR => 2,
            self::CHILEAN_PESO => 0,
            self::CHINESE_YUAN => 2,
            self::COLOMBIAN_PESO => 2,
            self::COMORIAN_FRANC => 0,
            self::CONGOLESE_FRANC => 2,
            self::COSTA_RICAN_COLON => 2,
            self::CROATIAN_KUNA => 2,
            self::CUBAN_PESO => 2,
            self::CZECH_KORUNA => 2,
            self::DANISH_KRONE => 2,
            self::DJIBOUTIAN_FRANC => 0,
            self::DOMINICAN_PESO => 2,
            self::EGYPTIAN_POUND => 2,
            self::SALVADORAN_COLON => 2,
            self::ERITREAN_NAKFA => 2,
            self::ESWATINI_LILANGENI => 2,
            self::ETHIOPIAN_BIRR => 2,
            self::FIJIAN_DOLLAR => 2,
            self::GAMBIAN_DALASI => 2,
            self::GEORGIAN_LARI => 2,
            self::GHANAIAN_CEDI => 2,
            self::GRENADIAN_DOLLAR => 2,
            self::GUATEMALAN_QUETZAL => 2,
            self::GUINEAN_FRANC => 0,
            self::GUYANESE_DOLLAR => 2,
            self::HAITIAN_GOURDE => 2,
            self::HONDURAN_LEMPIRA => 2,
            self::HUNGARIAN_FORINT => 2,
            self::ICELANDIC_KRONA => 0,
            self::INDIAN_RUPEE => 2,
            self::INDONESIAN_RUPIAH => 2,
            self::IRANIAN_RIAL => 2,
            self::IRAQI_DINAR => 3,
            self::ISRAELI_SHEKEL => 2,
            self::JAMAICAN_DOLLAR => 2,
            self::JAPANESE_YEN => 0,
            self::JORDANIAN_DINAR => 3,
            self::KAZAKHSTANI_TENGE => 2,
            self::KENYAN_SHILLING => 2,
            self::KIRIBATI_DOLLAR => 2,
            self::NORTH_KOREAN_WON => 2,
            self::SOUTH_KOREAN_WON => 0,
            self::KUWAITI_DINAR => 3,
            self::KYRGYZSTANI_SOM => 2,
            self::LAO_KIP => 2,
            self::LATVIAN_LATS => 2,
            self::LEBANESE_POUND => 2,
            self::LESOTHO_LOTI => 2,
            self::LIBERIAN_DOLLAR => 2,
            self::LIBYAN_DINAR => 3,
            self::LITHUANIAN_LITAS => 2,
            self::MALAGASY_ARIARY => 2,
            self::MALAWIAN_KWACHA => 2,
            self::MALAYSIAN_RINGGIT => 2,
            self::MALDIVIAN_RUFIYAA => 2,
            self::MAURITANIAN_OUGUIYA => 2,
            self::MAURITIAN_RUPEE => 2,
            self::MEXICAN_PESO => 2,
            self::MOLDOVAN_LEU => 2,
            self::MONGOLIAN_TUGRIK => 2,
            self::MOROCCAN_DIRHAM => 2,
            self::MOZAMBICAN_METICAL => 2,
            self::MYANMA_KYAT => 2,
            self::NAMIBIAN_DOLLAR => 2,
            self::NEPALESE_RUPEE => 2,
            self::NEW_ZEALAND_DOLLAR => 2,
            self::NICARAGUAN_CORDOBA => 2,
            self::NIGERIAN_NAIRA => 2,
            self::MACEDONIAN_DENAR => 2,
            self::NORWEGIAN_KRONE => 2,
            self::OMANI_RIAL => 3,
            self::PAKISTANI_RUPEE => 2,
            self::PANAMANIAN_BALBOA => 2,
            self::PAPUA_NEW_GUINEAN_KINA => 2,
            self::PARAGUAYAN_GUARANI => 0,
            self::PERUVIAN_SOL => 2,
            self::PHILIPPINE_PESO => 2,
            self::POLISH_ZLOTY => 2,
            self::QATARI_RIAL => 2,
            self::ROMANIAN_LEU => 2,
            self::RUSSIAN_RUBLE => 2,
            self::RWANDAN_FRANC => 0,
            self::SAUDI_RIYAL => 2,
            self::SERBIAN_DINAR => 2,
            self::SEYCHELLOIS_RUPEE => 2,
            self::SIERRA_LEONEAN_LEONE => 2,
            self::SINGAPORE_DOLLAR => 2,
            self::SOLOMON_ISLANDS_DOLLAR => 2,
            self::SOMALI_SHILLING => 2,
            self::SOUTH_AFRICAN_RAND => 2,
            self::SOUTH_SUDANESE_POUND => 2,
            self::SRI_LANKAN_RUPEE => 2,
            self::SUDANESE_POUND => 2,
            self::SURINAMESE_DOLLAR => 2,
            self::SWEDISH_KRONA => 2,
            self::SWISS_FRANC => 2,
            self::SYRIAN_POUND => 2,
            self::TAIWANESE_DOLLAR => 2,
            self::TAJIKISTANI_SOMONI => 2,
            self::TANZANIAN_SHILLING => 2,
            self::THAI_BAHT => 2,
            self::TONGAN_PAANGA => 2,
            self::TRINIDAD_AND_TOBAGO_DOLLAR => 2,
            self::TUNISIAN_DINAR => 3,
            self::TURKISH_LIRA => 2,
            self::TURKMENISTANI_MANAT => 2,
            self::UGANDAN_SHILLING => 2,
            self::UKRAINIAN_HRYVNIA => 2,
            self::UAE_DIRHAM => 2,
            self::BRITISH_POUND => 2,
            self::US_DOLLAR => 2,
            self::URUGUAYAN_PESO => 2,
            self::UZBEKISTANI_SOM => 2,
            self::VANUATU_VATU => 0,
            self::VENEZUELAN_BOLIVAR => 2,
            self::VIETNAMESE_DONG => 0,
            self::YEMENI_RIAL => 2,
            self::ZAMBIAN_KWACHA => 2,
            self::ZIMBABWEAN_DOLLAR => 2,
            self::CFA_FRANC_BCEAO => 0,
            self::CFA_FRANC_BEAC => 0,
            self::CFP_FRANC => 0,
            self::NETHERLANDS_ANTILLEAN_GUILDER => 2,
            self::ARUBAN_FLORIN => 2,
            self::HONG_KONG_DOLLAR => 2,
            self::MACANESE_PATACA => 2,
            default => null,
        };
    }

    /**
     * Returns the anchor currency of the currency or `null` if the currency has no anchor currency associated.
     * The returned currency is an instance of the {@see \Talp1\LaravelRegistry\Enums\Currencies} enum.
     *
     * @link https://en.wikipedia.org/wiki/List_of_circulating_fixed_exchange_rate_currencies
     */
    public function anchorCurrency(): ?self {
        return match ($this) {
            self::EAST_CARIBBEAN_DOLLAR => self::US_DOLLAR,
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => self::EURO,
            self::CFA_FRANC_BCEAO => self::EURO,
            self::CFA_FRANC_BEAC => self::EURO,
            self::CFP_FRANC => self::EURO,
            self::NETHERLANDS_ANTILLEAN_GUILDER => self::US_DOLLAR,
            self::ARUBAN_FLORIN => self::US_DOLLAR,
            self::BOLIVIAN_BOLIVIANO => self::US_DOLLAR,
            self::BULGARIAN_LEV => self::EURO,
            self::CABO_VERDE_ESCUDO => self::EURO,
            self::COMORIAN_FRANC => self::EURO,
            self::DJIBOUTIAN_FRANC => self::US_DOLLAR,
            self::DOMINICAN_PESO => self::US_DOLLAR,
            self::ERITREAN_NAKFA => self::US_DOLLAR,
            self::HONG_KONG_DOLLAR => self::US_DOLLAR,
            self::JORDANIAN_DINAR => self::US_DOLLAR,
            self::KUWAITI_DINAR => self::US_DOLLAR,
            self::LEBANESE_POUND => self::US_DOLLAR,
            self::MACANESE_PATACA => self::HONG_KONG_DOLLAR,
            self::MALDIVIAN_RUFIYAA => self::US_DOLLAR,
            self::MOROCCAN_DIRHAM => self::EURO,
            self::NAMIBIAN_DOLLAR => self::SOUTH_AFRICAN_RAND,
            self::OMANI_RIAL => self::US_DOLLAR,
            self::QATARI_RIAL => self::US_DOLLAR,
            self::SAUDI_RIYAL => self::US_DOLLAR,
            self::SINGAPORE_DOLLAR => self::US_DOLLAR,
            self::SOLOMON_ISLANDS_DOLLAR => self::AUSTRALIAN_DOLLAR,
            self::UAE_DIRHAM => self::US_DOLLAR,
            self::VENEZUELAN_BOLIVAR => self::US_DOLLAR,
            default => null,
        };
    }

    /**
     * Returns whether the currency has an anchor currency associated.
     */
    public function hasAnchorCurrency(): bool {
        return $this->anchorCurrency() !== null;
    }

    /**
     * Returns the fractional unit of the currency as an instance of the {@see \Talp1\LaravelRegistry\Enums\CurrencyFractionalUnits} enum
     * or `null` if the currency does not have a decimal representation.
     *
     * @link https://en.wikipedia.org/wiki/List_of_circulating_currencies
     */
    public function fractionalUnit(): ?CurrencyFractionalUnits {
        return match ($this) {
            self::AFGHANI => CurrencyFractionalUnits::PUL,
            self::ALBANIAN_LEK => CurrencyFractionalUnits::QINDARKA,
            self::ALGERIAN_DINAR => CurrencyFractionalUnits::CENT,
            self::EURO => CurrencyFractionalUnits::CENT,
            self::ANGOLAN_KWANZA => CurrencyFractionalUnits::CENT,
            self::EAST_CARIBBEAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::ARGENTINE_PESO => CurrencyFractionalUnits::CENT,
            self::ARMENIAN_DRAM => CurrencyFractionalUnits::LUMA,
            self::AUSTRALIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::AZERBAIJANI_MANAT => CurrencyFractionalUnits::GAPIK,
            self::BAHAMIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::BAHRAINI_DINAR => CurrencyFractionalUnits::FIL,
            self::BANGLADESHI_TAKA => CurrencyFractionalUnits::PAISA,
            self::BARBADIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::BELARUSIAN_RUBLE => CurrencyFractionalUnits::KAPIEK,
            self::BELIZE_DOLLAR => CurrencyFractionalUnits::CENT,
            self::BHUTANESE_NGULTRUM => CurrencyFractionalUnits::CHETRUM,
            self::BOLIVIAN_BOLIVIANO => CurrencyFractionalUnits::CENT,
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => CurrencyFractionalUnits::FENING,
            self::BOTSWANA_PULA => CurrencyFractionalUnits::THEBE,
            self::BRAZILIAN_REAL => CurrencyFractionalUnits::CENT,
            self::BRUNEIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::BULGARIAN_LEV => CurrencyFractionalUnits::STOTINKA,
            self::BURUNDIAN_FRANC => null,
            self::CABO_VERDE_ESCUDO => CurrencyFractionalUnits::CENT,
            self::CAMBODIAN_RIEL => CurrencyFractionalUnits::CENT,
            self::CANADIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::CHILEAN_PESO => CurrencyFractionalUnits::CENT,
            self::CHINESE_YUAN => CurrencyFractionalUnits::FEN,
            self::COLOMBIAN_PESO => CurrencyFractionalUnits::CENT,
            self::COMORIAN_FRANC => null,
            self::CONGOLESE_FRANC => CurrencyFractionalUnits::CENT,
            self::COSTA_RICAN_COLON => CurrencyFractionalUnits::CENT,
            self::CROATIAN_KUNA => CurrencyFractionalUnits::LIPA,
            self::CUBAN_PESO => CurrencyFractionalUnits::CENT,
            self::CZECH_KORUNA => CurrencyFractionalUnits::HALER,
            self::DANISH_KRONE => CurrencyFractionalUnits::ORE,
            self::DJIBOUTIAN_FRANC => null,
            self::DOMINICAN_PESO => CurrencyFractionalUnits::CENT,
            self::EGYPTIAN_POUND => CurrencyFractionalUnits::PIASTRE,
            self::SALVADORAN_COLON => CurrencyFractionalUnits::CENT,
            self::ERITREAN_NAKFA => CurrencyFractionalUnits::CENT,
            self::ESWATINI_LILANGENI => CurrencyFractionalUnits::CENT,
            self::ETHIOPIAN_BIRR => CurrencyFractionalUnits::CENT,
            self::FIJIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::GAMBIAN_DALASI => CurrencyFractionalUnits::BUTUT,
            self::GEORGIAN_LARI => CurrencyFractionalUnits::TETRI,
            self::GHANAIAN_CEDI => CurrencyFractionalUnits::PESAWA,
            self::GUATEMALAN_QUETZAL => CurrencyFractionalUnits::CENT,
            self::GUINEAN_FRANC => null,
            self::GUYANESE_DOLLAR => CurrencyFractionalUnits::CENT,
            self::HAITIAN_GOURDE => CurrencyFractionalUnits::CENT,
            self::HONDURAN_LEMPIRA => CurrencyFractionalUnits::CENT,
            self::HUNGARIAN_FORINT => CurrencyFractionalUnits::FILLER,
            self::ICELANDIC_KRONA => CurrencyFractionalUnits::AURAR,
            self::INDIAN_RUPEE => CurrencyFractionalUnits::PAISA,
            self::INDONESIAN_RUPIAH => CurrencyFractionalUnits::CENT,
            self::IRANIAN_RIAL => CurrencyFractionalUnits::DINAR,
            self::IRAQI_DINAR => CurrencyFractionalUnits::FIL,
            self::ISRAELI_SHEKEL => CurrencyFractionalUnits::AGORA,
            self::JAMAICAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::JAPANESE_YEN => CurrencyFractionalUnits::CENT,
            self::JORDANIAN_DINAR => CurrencyFractionalUnits::PIASTRE,
            self::KAZAKHSTANI_TENGE => CurrencyFractionalUnits::TIYIN,
            self::KENYAN_SHILLING => CurrencyFractionalUnits::CENT,
            self::KIRIBATI_DOLLAR => CurrencyFractionalUnits::CENT,
            self::NORTH_KOREAN_WON => CurrencyFractionalUnits::CHON,
            self::SOUTH_KOREAN_WON => CurrencyFractionalUnits::JEON,
            self::KUWAITI_DINAR => CurrencyFractionalUnits::FIL,
            self::KYRGYZSTANI_SOM => CurrencyFractionalUnits::TIYIN,
            self::LAO_KIP => CurrencyFractionalUnits::ATT,
            self::LATVIAN_LATS => CurrencyFractionalUnits::CENT,
            self::LEBANESE_POUND => CurrencyFractionalUnits::PIASTRE,
            self::LESOTHO_LOTI => CurrencyFractionalUnits::CENT,
            self::LIBERIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::LIBYAN_DINAR => CurrencyFractionalUnits::DIRHAM,
            self::LITHUANIAN_LITAS => CurrencyFractionalUnits::CENT,
            self::MALAGASY_ARIARY => CurrencyFractionalUnits::IRAIMBILANJA,
            self::MALAWIAN_KWACHA => CurrencyFractionalUnits::TAMBALA,
            self::MALAYSIAN_RINGGIT => CurrencyFractionalUnits::CENT,
            self::MALDIVIAN_RUFIYAA => CurrencyFractionalUnits::LAARI,
            self::MAURITANIAN_OUGUIYA => CurrencyFractionalUnits::KHOUMS,
            self::MAURITIAN_RUPEE => CurrencyFractionalUnits::CENT,
            self::MEXICAN_PESO => CurrencyFractionalUnits::CENT,
            self::MOLDOVAN_LEU => CurrencyFractionalUnits::BAN,
            self::MONGOLIAN_TUGRIK => CurrencyFractionalUnits::MONGO,
            self::MOROCCAN_DIRHAM => CurrencyFractionalUnits::CENT,
            self::MOZAMBICAN_METICAL => CurrencyFractionalUnits::CENT,
            self::MYANMA_KYAT => CurrencyFractionalUnits::PYA,
            self::NAMIBIAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::NEPALESE_RUPEE => CurrencyFractionalUnits::PAISA,
            self::NEW_ZEALAND_DOLLAR => CurrencyFractionalUnits::CENT,
            self::NICARAGUAN_CORDOBA => CurrencyFractionalUnits::CENT,
            self::NIGERIAN_NAIRA => CurrencyFractionalUnits::KOBO,
            self::MACEDONIAN_DENAR => CurrencyFractionalUnits::DENI,
            self::NORWEGIAN_KRONE => CurrencyFractionalUnits::ORE,
            self::OMANI_RIAL => CurrencyFractionalUnits::BAISA,
            self::PAKISTANI_RUPEE => CurrencyFractionalUnits::PAISA,
            self::PANAMANIAN_BALBOA => CurrencyFractionalUnits::CENT,
            self::PAPUA_NEW_GUINEAN_KINA => CurrencyFractionalUnits::TOEA,
            self::PARAGUAYAN_GUARANI => CurrencyFractionalUnits::CENT,
            self::PERUVIAN_SOL => CurrencyFractionalUnits::CENT,
            self::PHILIPPINE_PESO => CurrencyFractionalUnits::CENT,
            self::POLISH_ZLOTY => CurrencyFractionalUnits::GROSZ,
            self::QATARI_RIAL => CurrencyFractionalUnits::DIRHAM,
            self::ROMANIAN_LEU => CurrencyFractionalUnits::BAN,
            self::RUSSIAN_RUBLE => CurrencyFractionalUnits::KOPEK,
            self::RWANDAN_FRANC => CurrencyFractionalUnits::CENT,
            self::SAMOAN_TALA => CurrencyFractionalUnits::SENE,
            self::SAO_TOME_AND_PRINCIPE_DOBRA => CurrencyFractionalUnits::CENT,
            self::SAUDI_RIYAL => CurrencyFractionalUnits::HALALA,
            self::SERBIAN_DINAR => CurrencyFractionalUnits::PARA,
            self::SEYCHELLOIS_RUPEE => CurrencyFractionalUnits::CENT,
            self::SIERRA_LEONEAN_LEONE => CurrencyFractionalUnits::CENT,
            self::SINGAPORE_DOLLAR => CurrencyFractionalUnits::CENT,
            self::SOLOMON_ISLANDS_DOLLAR => CurrencyFractionalUnits::CENT,
            self::SOMALI_SHILLING => CurrencyFractionalUnits::CENT,
            self::SOUTH_AFRICAN_RAND => CurrencyFractionalUnits::CENT,
            self::SOUTH_SUDANESE_POUND => CurrencyFractionalUnits::PIASTRE,
            self::SRI_LANKAN_RUPEE => CurrencyFractionalUnits::CENT,
            self::SUDANESE_POUND => CurrencyFractionalUnits::PIASTRE,
            self::SURINAMESE_DOLLAR => CurrencyFractionalUnits::CENT,
            self::SWEDISH_KRONA => CurrencyFractionalUnits::ORE,
            self::SWISS_FRANC => CurrencyFractionalUnits::RAPPEN,
            self::SYRIAN_POUND => CurrencyFractionalUnits::PIASTRE,
            self::TAJIKISTANI_SOMONI => CurrencyFractionalUnits::DIRHAM,
            self::TANZANIAN_SHILLING => CurrencyFractionalUnits::CENT,
            self::THAI_BAHT => CurrencyFractionalUnits::SATANG,
            self::TONGAN_PAANGA => CurrencyFractionalUnits::CENT,
            self::TRINIDAD_AND_TOBAGO_DOLLAR => CurrencyFractionalUnits::CENT,
            self::TUNISIAN_DINAR => CurrencyFractionalUnits::MILLIEME,
            self::TURKISH_LIRA => CurrencyFractionalUnits::KURUS,
            self::TURKMENISTANI_MANAT => CurrencyFractionalUnits::TENNESI,
            self::UGANDAN_SHILLING => CurrencyFractionalUnits::CENT,
            self::UKRAINIAN_HRYVNIA => CurrencyFractionalUnits::KOPIYKA,
            self::UAE_DIRHAM => CurrencyFractionalUnits::FIL,
            self::BRITISH_POUND => CurrencyFractionalUnits::PENNY,
            self::US_DOLLAR => CurrencyFractionalUnits::CENT,
            self::URUGUAYAN_PESO => CurrencyFractionalUnits::CENT,
            self::UZBEKISTANI_SOM => CurrencyFractionalUnits::TIYIN,
            self::VENEZUELAN_BOLIVAR => CurrencyFractionalUnits::CENT,
            self::VIETNAMESE_DONG => CurrencyFractionalUnits::HAO,
            self::YEMENI_RIAL => CurrencyFractionalUnits::FIL,
            self::ZAMBIAN_KWACHA => CurrencyFractionalUnits::NGWEE,
            self::ZIMBABWEAN_DOLLAR => CurrencyFractionalUnits::CENT,
            self::CFA_FRANC_BCEAO => CurrencyFractionalUnits::CENT,
            self::CFA_FRANC_BEAC => CurrencyFractionalUnits::CENT,
            self::CFP_FRANC => CurrencyFractionalUnits::CENT,
            self::NETHERLANDS_ANTILLEAN_GUILDER => CurrencyFractionalUnits::CENT,
            self::ARUBAN_FLORIN => CurrencyFractionalUnits::CENT,
            self::HONG_KONG_DOLLAR => CurrencyFractionalUnits::CENT,
            self::MACANESE_PATACA => CurrencyFractionalUnits::AVO,
            default => null,
        };
    }

    /**
     * Returns the amount of fractional units needed to reach the value of a unit of the currency.
     * Returns `null` if the currency does not have a fractional unit.
     *
     * @link https://en.wikipedia.org/wiki/List_of_circulating_currencies
     */
    public function fractionsPerUnit(): ?int {
        return match ($this) {
            self::AFGHANI => 100,
            self::ALBANIAN_LEK => 100,
            self::ALGERIAN_DINAR => 100,
            self::EURO => 100,
            self::ANGOLAN_KWANZA => 100,
            self::EAST_CARIBBEAN_DOLLAR => 100,
            self::ARGENTINE_PESO => 100,
            self::ARMENIAN_DRAM => 100,
            self::AUSTRALIAN_DOLLAR => 100,
            self::AZERBAIJANI_MANAT => 100,
            self::BAHAMIAN_DOLLAR => 100,
            self::BAHRAINI_DINAR => 1000,
            self::BANGLADESHI_TAKA => 100,
            self::BARBADIAN_DOLLAR => 100,
            self::BELARUSIAN_RUBLE => 100,
            self::BELIZE_DOLLAR => 100,
            self::BHUTANESE_NGULTRUM => 100,
            self::BOLIVIAN_BOLIVIANO => 100,
            self::BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK => 100,
            self::BOTSWANA_PULA => 100,
            self::BRAZILIAN_REAL => 100,
            self::BRUNEIAN_DOLLAR => 100,
            self::BULGARIAN_LEV => 100,
            self::BURUNDIAN_FRANC => null,
            self::CABO_VERDE_ESCUDO => 100,
            self::CAMBODIAN_RIEL => 100,
            self::CANADIAN_DOLLAR => 100,
            self::CHILEAN_PESO => 100,
            self::CHINESE_YUAN => 100,
            self::COLOMBIAN_PESO => 100,
            self::COMORIAN_FRANC => null,
            self::CONGOLESE_FRANC => 100,
            self::COSTA_RICAN_COLON => 100,
            self::CROATIAN_KUNA => 100,
            self::CUBAN_PESO => 100,
            self::CZECH_KORUNA => 100,
            self::DANISH_KRONE => 100,
            self::DJIBOUTIAN_FRANC => null,
            self::DOMINICAN_PESO => 100,
            self::EGYPTIAN_POUND => 100,
            self::SALVADORAN_COLON => 100,
            self::ERITREAN_NAKFA => 100,
            self::ESWATINI_LILANGENI => 100,
            self::ETHIOPIAN_BIRR => 100,
            self::FIJIAN_DOLLAR => 100,
            self::GAMBIAN_DALASI => 100,
            self::GEORGIAN_LARI => 100,
            self::GHANAIAN_CEDI => 100,
            self::GUATEMALAN_QUETZAL => 100,
            self::GUINEAN_FRANC => null,
            self::GUYANESE_DOLLAR => 100,
            self::HAITIAN_GOURDE => 100,
            self::HONDURAN_LEMPIRA => 100,
            self::HUNGARIAN_FORINT => 100,
            self::ICELANDIC_KRONA => 100,
            self::INDIAN_RUPEE => 100,
            self::INDONESIAN_RUPIAH => 100,
            self::IRANIAN_RIAL => 100,
            self::IRAQI_DINAR => 1000,
            self::ISRAELI_SHEKEL => 100,
            self::JAMAICAN_DOLLAR => 100,
            self::JAPANESE_YEN => 100,
            self::JORDANIAN_DINAR => 1000,
            self::KAZAKHSTANI_TENGE => 100,
            self::KENYAN_SHILLING => 100,
            self::KIRIBATI_DOLLAR => 100,
            self::NORTH_KOREAN_WON => 100,
            self::SOUTH_KOREAN_WON => 100,
            self::KUWAITI_DINAR => 1000,
            self::KYRGYZSTANI_SOM => 100,
            self::LAO_KIP => 100,
            self::LATVIAN_LATS => 100,
            self::LEBANESE_POUND => 100,
            self::LESOTHO_LOTI => 100,
            self::LIBERIAN_DOLLAR => 100,
            self::LIBYAN_DINAR => 1000,
            self::LITHUANIAN_LITAS => 100,
            self::MALAGASY_ARIARY => 100,
            self::MALAWIAN_KWACHA => 100,
            self::MALAYSIAN_RINGGIT => 100,
            self::MALDIVIAN_RUFIYAA => 100,
            self::MAURITANIAN_OUGUIYA => 100,
            self::MAURITIAN_RUPEE => 100,
            self::MEXICAN_PESO => 100,
            self::MOLDOVAN_LEU => 100,
            self::MONGOLIAN_TUGRIK => 100,
            self::MOROCCAN_DIRHAM => 100,
            self::MOZAMBICAN_METICAL => 100,
            self::MYANMA_KYAT => 100,
            self::NAMIBIAN_DOLLAR => 100,
            self::NEPALESE_RUPEE => 100,
            self::NEW_ZEALAND_DOLLAR => 100,
            self::NICARAGUAN_CORDOBA => 100,
            self::NIGERIAN_NAIRA => 100,
            self::MACEDONIAN_DENAR => 100,
            self::NORWEGIAN_KRONE => 100,
            self::OMANI_RIAL => 1000,
            self::PAKISTANI_RUPEE => 100,
            self::PANAMANIAN_BALBOA => 100,
            self::PAPUA_NEW_GUINEAN_KINA => 100,
            self::PARAGUAYAN_GUARANI => 100,
            self::PERUVIAN_SOL => 100,
            self::PHILIPPINE_PESO => 100,
            self::POLISH_ZLOTY => 100,
            self::QATARI_RIAL => 100,
            self::ROMANIAN_LEU => 100,
            self::RUSSIAN_RUBLE => 100,
            self::RWANDAN_FRANC => 100,
            self::SAMOAN_TALA => 100,
            self::SAO_TOME_AND_PRINCIPE_DOBRA => 100,
            self::SAUDI_RIYAL => 100,
            self::SENEGALESE_FRANC => 100,
            self::SERBIAN_DINAR => 100,
            self::SEYCHELLOIS_RUPEE => 100,
            self::SIERRA_LEONEAN_LEONE => 100,
            self::SINGAPORE_DOLLAR => 100,
            self::SOLOMON_ISLANDS_DOLLAR => 100,
            self::SOMALI_SHILLING => 100,
            self::SOUTH_AFRICAN_RAND => 100,
            self::SOUTH_SUDANESE_POUND => 100,
            self::SRI_LANKAN_RUPEE => 100,
            self::SUDANESE_POUND => 100,
            self::SURINAMESE_DOLLAR => 100,
            self::SWEDISH_KRONA => 100,
            self::SWISS_FRANC => 100,
            self::SYRIAN_POUND => 100,
            self::TAJIKISTANI_SOMONI => 100,
            self::TANZANIAN_SHILLING => 100,
            self::THAI_BAHT => 100,
            self::TONGAN_PAANGA => 100,
            self::TRINIDAD_AND_TOBAGO_DOLLAR => 100,
            self::TUNISIAN_DINAR => 1000,
            self::TURKISH_LIRA => 100,
            self::TURKMENISTANI_MANAT => 100,
            self::UGANDAN_SHILLING => 100,
            self::UKRAINIAN_HRYVNIA => 100,
            self::UAE_DIRHAM => 100,
            self::BRITISH_POUND => 100,
            self::US_DOLLAR => 100,
            self::URUGUAYAN_PESO => 100,
            self::UZBEKISTANI_SOM => 100,
            self::VENEZUELAN_BOLIVAR => 100,
            self::VIETNAMESE_DONG => 100,
            self::YEMENI_RIAL => 100,
            self::ZAMBIAN_KWACHA => 100,
            self::ZIMBABWEAN_DOLLAR => 100,
            self::CFA_FRANC_BCEAO => 100,
            self::CFA_FRANC_BEAC => 100,
            self::CFP_FRANC => 100,
            self::NETHERLANDS_ANTILLEAN_GUILDER => 100,
            self::ARUBAN_FLORIN => 100,
            self::HONG_KONG_DOLLAR => 100,
            self::MACANESE_PATACA => 100,
            default => null,
        };
    }
}
