<?php

namespace Talp1\LaravelRegistry\Enums;

use Talp1\LaravelRegistry\Enums\Contracts\CanBeCollected;
use Talp1\LaravelRegistry\Enums\Contracts\HasLabels;
use Talp1\LaravelRegistry\Enums\Contracts\HasRandom;
use Talp1\LaravelRegistry\Enums\Traits\CanBeCollected as CanBeCollectedTrait;
use Talp1\LaravelRegistry\Enums\Traits\ConvertsValueToLabel;
use Talp1\LaravelRegistry\Enums\Traits\HasRandom as HasRandomTrait;

/**
 * Enum of all the e-mail address providers.
 *
 * Note that the list or its bindings may be incomplete or not up-to-date.
 * If you find an error or an inconsistency, please open an issue or a pull request at {@link https://github.com/Talpx1/laravel-registry}
 *
 * @implements CanBeCollected<string>
 * @implements HasRandom<string>
 */
enum EmailAddressProviders: string implements CanBeCollected, HasLabels, HasRandom {
    /**
     * @use CanBeCollectedTrait<string>
     * @use HasRandomTrait<string>
     */
    use CanBeCollectedTrait, ConvertsValueToLabel, HasRandomTrait;

    case _123MAIL = '123 mail';
    case _150MAIL = '150 mail';
    case _150ML = '150 ml';
    case _16MAIL = '16 mail';
    case _2MAIL = '2 mail';
    case _4EMAIL = '4 email';
    case _50MAIL = '50 mail';
    case AIM = 'aim';
    case AIRPOST = 'airpost';
    case ALICE = 'alice';
    case ALICEADSL = 'aliceadsl';
    case ALLMAIL = 'allmail';
    case AOL = 'aol';
    case ARCOR = 'arcor';
    case ARUBA = 'aruba';
    case ATT = 'att';
    case ATTORNEYMAIL = 'attorneymail';
    case BARMAIL = 'barmail';
    case BELLSOUTH = 'bellsouth';
    case BESTMAIL = 'bestmail';
    case BIGPOND = 'bigpond';
    case BK = 'bk';
    case BLUEWIN = 'bluewin';
    case BLUEYONDER = 'blueyonder';
    case BOL = 'bol';
    case CENTURYTEL = 'centurytel';
    case CHARTER = 'charter';
    case CHELLO = 'chello';
    case CLUB_INTERNET = 'club internet';
    case CLUEMAIL = 'cluemail';
    case COLLABORATIVE = 'collaborative';
    case COMCAST = 'comcast';
    case COX = 'cox';
    case DIPLOMAIL = 'diplomail';
    case EARTHLINK = 'earthlink';
    case ELITEMAIL = 'elitemail';
    case EMAILCORNER = 'emailcorner';
    case EMAILENGINE = 'emailengine';
    case EMAILGROUPS = 'emailgroups';
    case EMAILPLUS = 'emailplus';
    case EMAILUSER = 'emailuser';
    case EML = 'eml';
    case EXCITE = 'excite';
    case F_M = 'f-m';
    case FACEBOOK = 'facebook';
    case FAST_EMAIL = 'fast email';
    case FAST_MAIL = 'fast mail';
    case FASTEM = 'fastem';
    case FASTEMAIL = 'fastemail';
    case FASTEMAILER = 'fastemailer';
    case FASTEST = 'fastest';
    case FASTIMAP = 'fastimap';
    case FASTMAIL = 'fastmail';
    case FASTMAILBOX = 'fastmailbox';
    case FASTMESSAGING = 'fastmessaging';
    case FEA = 'fea';
    case FMAIL = 'fmail';
    case FMAILBOX = 'fmailbox';
    case FMGIRL = 'fmgirl';
    case FMGUY = 'fmguy';
    case FREE = 'free';
    case FREEDOMMAIL = 'freedommail';
    case FREENET = 'freenet';
    case FRONTIERNET = 'frontiernet';
    case FTML = 'ftml';
    case GANDI = 'gandi';
    case GMAIL = 'gmail';
    case GMX = 'gmx';
    case GOOGLEMAIL = 'google mail';
    case GROUPOFFICE = 'groupoffice';
    case H_MAIL = 'h mail';
    case HAILMAIL = 'hailmail';
    case HETNET = 'hetnet';
    case HEY = 'hey';
    case HOME = 'home';
    case HOTMAIL = 'hotmail';
    case HUSHMAIL = 'hushmail';
    case ICLOUD = 'icloud';
    case IG = 'ig';
    case IMAP_MAIL = 'imap-mail';
    case IMAP = 'imap';
    case IMAPMAIL = 'imapmail';
    case INBOX = 'inbox';
    case INOUTBOX = 'inoutbox';
    case INTERNET_E_MAIL = 'internet e mail';
    case INTERNET_MAIL = 'internet mail';
    case INTERNET = 'internet';
    case INTERNETEMAILS = 'internetemails';
    case INTERNETMAILING = 'internetmailing';
    case JETEMAIL = 'jetemail';
    case JOURNALISTMAIL = 'journalistmail';
    case JUNO = 'juno';
    case JUSTEMAIL = 'justemail';
    case KEEMAIL = 'keemail';
    case KOLABNOW = 'kolabnow';
    case LAPOSTE = 'laposte';
    case LEGALPRIVILEGE = 'legalprivilege';
    case LETTERBOXES = 'letterboxes';
    case LIBERO = 'libero';
    case LIBERTYMAIL = 'libertymail';
    case LIST = 'list';
    case LIVE = 'live';
    case LYCOS = 'lycos';
    case MAC = 'mac';
    case MAIL_CENTRAL = 'mail central';
    case MAIL_PAGE = 'mail page';
    case MAIL = 'mail';
    case MAILANDFTP = 'mailandftp';
    case MAILATLAW = 'mailatlaw';
    case MAILBOLT = 'mailbolt';
    case MAILC = 'mailc';
    case MAILCAN = 'mailcan';
    case MAILFORCE = 'mailforce';
    case MAILFTP = 'mailftp';
    case MAILHAVEN = 'mailhaven';
    case MAILHOST = 'mailhost';
    case MAILHOUSE = 'mailhouse';
    case MAILINGADDRESS = 'mailingaddress';
    case MAILITE = 'mailite';
    case MAILMIGHT = 'mailmight';
    case MAILNEW = 'mailnew';
    case MAILSENT = 'mailsent';
    case MAILSERVICE = 'mailservice';
    case MAILUP = 'mailup';
    case MAILWORKS = 'mailworks';
    case ME = 'me';
    case MEDMAIL = 'medmail';
    case MESSAGEBOX = 'messagebox';
    case ML1 = 'ml1';
    case MM = 'mm';
    case MSN = 'msn';
    case MYFASTMAIL = 'myfastmail';
    case MYKOLAB = 'mykolab';
    case MYMACMAIL = 'mymacmail';
    case MYSWISSMAIL = 'myswissmail';
    case NEUF = 'neuf';
    case NOSPAMMAIL = 'nospammail';
    case NTLWORLD = 'ntlworld';
    case OFFSHORE = 'offshore';
    case OPENGROUPWARE = 'opengroupware';
    case OPTONLINE = 'optonline';
    case OPTUSNET = 'optusnet';
    case ORANGE = 'orange';
    case OUTLOOK = 'outlook';
    case OWNMAIL = 'ownmail';
    case PETML = 'petml';
    case PLANET = 'planet';
    case POSTEO = 'posteo';
    case POSTINBOX = 'postinbox';
    case POSTPRO = 'postpro';
    case PRESSMAIL = 'pressmail';
    case PROINBOX = 'proinbox';
    case PROMESSAGE = 'promessage';
    case PROTOMNMAIL = 'protomnmail';
    case QQ = 'qq';
    case RAMBLER = 'rambler';
    case RBOX = 'rbox';
    case RBX = 'rbx';
    case REALEMAIL = 'realemail';
    case REALLYFAST = 'reallyfast';
    case REDIFFMAIL = 'rediffmail';
    case RNBX = 'rnbx';
    case ROCKETMAIL = 'rocketmail';
    case RUNBOX = 'runbox';
    case RUSHPOST = 'rushpost';
    case SBCGLOBAL = 'sbcglobal';
    case SENT = 'sent';
    case SFR = 'sfr';
    case SHAW = 'shaw';
    case SKY = 'sky';
    case SKYNET = 'skynet';
    case SPEEDPOST = 'speedpost';
    case SPEEDYMAIL = 'speedymail';
    case SSL_MAIL = 'ssl mail';
    case SWIFT_MAIL = 'swift mail';
    case SWISSGROUPWARE = 'swissgroupware';
    case SWITZERLANDMAIL = 'switzerlandmail';
    case SYMPATICO = 'sympatico';
    case T_ONLINE = 't online';
    case TELENET = 'telenet';
    case TERRA = 'terra';
    case THE_FASTEST = 'the fastest';
    case THE_QUICKEST = 'the quickest';
    case THEINTERNETEMAIL = 'theinternetemail';
    case TIN = 'tin';
    case TISCALI = 'tiscali';
    case TRUSTED_LEGAL_MAIL = 'trusted legal mail';
    case TUTA = 'tuta';
    case TUTAMAIL = 'tutamail';
    case TUTANOTA = 'tutanota';
    case UOL = 'uol';
    case VERIZON = 'verizon';
    case VERYFAST = 'veryfast';
    case VERYSPEEDY = 'veryspeedy';
    case VIRGILIO = 'virgilio';
    case VOILA = 'voila';
    case WANADOO = 'wanadoo';
    case WARPMAIL = 'warpmail';
    case WEB = 'web';
    case WINDSTREAM = 'windstream';
    case XOBNUR = 'xobnur';
    case XSMAIL = 'xsmail';
    case YAHOO = 'yahoo';
    case YANDEX = 'yandex';
    case YEPMAIL = 'yepmail';
    case YMAIL = 'ymail';
    case YOUR_MAIL = 'your mail';
    case ZOHOMAIL = 'zohomail';
    case ZONNET = 'zonnet';
}
